{"abstract":[{"type":"text","text":"The test result represented by "},{"type":"codeVoice","code":"TestResult"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/pingonesdk\/notificationtest\/testresult-c.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/notificationtest\/testresult-c.property"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/testResult-c.property","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"testResult","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NotificationTest","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10PingOneSDK16NotificationTestC0E6ResultO","text":"TestResult","kind":"typeIdentifier"}],"externalID":"c:@M@PingOneSDK@objc(cs)NotificationTest(py)testResult","navigatorTitle":[{"text":"testResult","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"PingOneSDK"}],"title":"testResult","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"testResult","kind":"identifier"},{"kind":"text","text":": "},{"text":"NotificationTest","kind":"typeIdentifier","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest"},{"text":".","kind":"text"},{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum","kind":"typeIdentifier","preciseIdentifier":"s:10PingOneSDK16NotificationTestC0E6ResultO","text":"TestResult"}]}],"kind":"declarations"}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/testResult-c.property":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/testResult-c.property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"testResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NotificationTest","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest"},{"kind":"text","text":"."},{"text":"TestResult","kind":"typeIdentifier","preciseIdentifier":"s:10PingOneSDK16NotificationTestC0E6ResultO"}],"abstract":[{"type":"text","text":"The test result represented by "},{"code":"TestResult","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"testResult","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/notificationtest\/testresult-c.property","kind":"symbol","role":"symbol","type":"topic","title":"testResult"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/TestResult-swift.enum":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TestResult"}],"navigatorTitle":[{"kind":"identifier","text":"TestResult"}],"abstract":[{"type":"text","text":"Public enum that describes the notification test result."}],"title":"NotificationTest.TestResult","url":"\/documentation\/pingonesdk\/notificationtest\/testresult-swift.enum"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/TestResult":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/TestResult","title":"TestResult","abstract":[{"type":"text","text":"Public enum that describes the notification test result."}],"url":"\/documentation\/pingonesdk\/testresult","fragments":[{"kind":"identifier","text":"TestResult"}],"type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","title":"NotificationTest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NotificationTest","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"NotificationTest","kind":"identifier"}],"abstract":[{"type":"text","text":"Public class that contains data of notifications tests"}],"role":"symbol","type":"topic","url":"\/documentation\/pingonesdk\/notificationtest"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"testResult","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"testResult"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@PingOneSDK@E@TestResult","text":"TestResult","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/TestResult","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"testResult","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"testResult","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest~1testResult-c.property\/title","op":"replace"},{"value":[{"kind":"identifier","text":"testResult"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest~1testResult-c.property\/fragments"},{"value":"NotificationTest","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/title"},{"value":[{"text":"NotificationTest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/fragments"}]}]}