{"abstract":[{"type":"text","text":"Public class that contains data of authenticate with code response"}],"topicSections":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/clientContext","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/status","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/userApproval","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/users"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/approve(userId:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/deny(_:completionHandler:)"]}],"sections":[],"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"AuthenticationObject"}],"title":"AuthenticationObject","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationObject"}],"externalID":"c:@M@PingOneSDK@objc(cs)AuthenticationObject","roleHeading":"Class","role":"symbol","modules":[{"name":"PingOneSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationObject"}]}]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/pingonesdk\/authenticationobject"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/authenticationobject"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/SQ","doc:\/\/com.pingIdentity.PingOneSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject/clientContext":{"navigatorTitle":[{"text":"clientContext","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/authenticationobject\/clientcontext","title":"clientContext","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/clientContext","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientContext"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Object for passing any data as a String from server to end-user"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.pingIdentity.PingOneSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.pingIdentity.PingOneSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pingIdentity.PingOneSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject/init":{"url":"\/documentation\/pingonesdk\/authenticationobject\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","title":"init","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/init","abstract":[],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/SH":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject/approve(userId:completionHandler:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"approveWithUserId:completionHandler:"}],"type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/approve(userId:completionHandler:)","kind":"symbol","abstract":[{"type":"text","text":"Approve authentication with code"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"approve"},{"kind":"text","text":"("},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"status"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"url":"\/documentation\/pingonesdk\/authenticationobject\/approve(userid:completionhandler:)","title":"approve(userId:completionHandler:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject/userApproval":{"title":"userApproval","navigatorTitle":[{"text":"userApproval","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userApproval"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/userApproval","abstract":[{"text":"String that determines if user approval is required to complete an authentication. Possible values: ","type":"text"},{"type":"codeVoice","code":"REQUIRED"},{"text":" and ","type":"text"},{"code":"NOT_REQUIRED","type":"codeVoice"}],"url":"\/documentation\/pingonesdk\/authenticationobject\/userapproval"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject":{"type":"topic","role":"symbol","url":"\/documentation\/pingonesdk\/authenticationobject","abstract":[{"text":"Public class that contains data of authenticate with code response","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationObject"}],"kind":"symbol","title":"AuthenticationObject","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject","navigatorTitle":[{"text":"AuthenticationObject","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SQ","title":"Swift.Equatable"},"doc://com.pingIdentity.PingOneSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject/deny(_:completionHandler:)":{"type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/deny(_:completionHandler:)","url":"\/documentation\/pingonesdk\/authenticationobject\/deny(_:completionhandler:)","abstract":[{"type":"text","text":"Deny authentication with code"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deny","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"title":"deny(_:completionHandler:)","navigatorTitle":[{"text":"deny:completionHandler:","kind":"identifier"}],"role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject/users":{"type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/users","url":"\/documentation\/pingonesdk\/authenticationobject\/users","abstract":[{"text":"List of users that are paired to this device. Each user object can contain the following String variables: ","type":"text"},{"type":"codeVoice","code":"userId"},{"type":"text","text":", "},{"type":"codeVoice","code":"email"},{"type":"text","text":", "},{"code":"given","type":"codeVoice"},{"text":", ","type":"text"},{"code":"family","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"username","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"users"},{"kind":"text","text":": [["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]]?","kind":"text"}],"title":"users","navigatorTitle":[{"text":"users","kind":"identifier"}],"role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject/status":{"kind":"symbol","url":"\/documentation\/pingonesdk\/authenticationobject\/status","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"status","kind":"identifier"}],"abstract":[{"type":"text","text":"String value returned from a server when a user calls an authenticate API method. Possible values: can be "},{"code":"CLAIMED","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"EXPIRED"},{"text":", ","type":"text"},{"code":"DENIED","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"COMPLETED"}],"title":"status","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/status"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","url":"\/documentation\/pingonesdk","role":"collection","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AuthenticationObject","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AuthenticationObject"}],"op":"replace"},{"value":[{"kind":"identifier","text":"AuthenticationObject"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/clientContext","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/status","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/userApproval","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/users"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/approve(userId:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/deny(_:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/init"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationObject"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1clientContext\/title","value":"clientContext"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1clientContext\/fragments","value":[{"kind":"identifier","text":"clientContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1approve(userId:completionHandler:)\/title","value":"approveWithUserId:completionHandler:"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1approve(userId:completionHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"approveWithUserId:completionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1userApproval\/title","op":"replace","value":"userApproval"},{"value":[{"kind":"identifier","text":"userApproval"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1userApproval\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/title","op":"replace","value":"AuthenticationObject"},{"value":[{"kind":"identifier","text":"AuthenticationObject"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1deny(_:completionHandler:)\/title","value":"deny:completionHandler:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"deny:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1deny(_:completionHandler:)\/fragments"},{"value":"users","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1users\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1users\/fragments","value":[{"text":"users","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1status\/title","value":"status","op":"replace"},{"value":[{"text":"status","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1status\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}