{"kind":"symbol","abstract":[{"type":"text","text":"AuthenticatorModel public class contains the acceptable authorization methods and its status"}],"metadata":{"title":"AuthenticatorModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AuthenticatorModel","kind":"identifier"}],"role":"symbol","symbolKind":"class","externalID":"c:@M@PingOneSDK@objc(cs)AuthenticatorModel","modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticatorModel"}],"roleHeading":"Class"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/errorCode","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/errorMessage","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/status","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/type"],"title":"Instance Properties"},{"title":"Enumerations","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/AuthenticatorStatus","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/AuthenticatorType"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/SQ","doc:\/\/com.pingIdentity.PingOneSDK\/SH"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticatorModel"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/authenticatormodel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/authenticatormodel"]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel/errorCode":{"title":"errorCode","type":"topic","role":"symbol","url":"\/documentation\/pingonesdk\/authenticatormodel\/errorcode","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorCode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"abstract":[{"text":"Error message in case of authorization method failure","type":"text"}],"navigatorTitle":[{"text":"errorCode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/errorCode"},"doc://com.pingIdentity.PingOneSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.pingIdentity.PingOneSDK/SQ":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pingIdentity.PingOneSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel":{"type":"topic","title":"AuthenticatorModel","role":"symbol","url":"\/documentation\/pingonesdk\/authenticatormodel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticatorModel","kind":"identifier"}],"abstract":[{"text":"AuthenticatorModel public class contains the acceptable authorization methods and its status","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticatorModel"}],"kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel"},"doc://com.pingIdentity.PingOneSDK/SH":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel/status":{"type":"topic","title":"status","role":"symbol","url":"\/documentation\/pingonesdk\/authenticatormodel\/status","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10PingOneSDK18AuthenticatorModelC0D6StatusO","text":"AuthenticatorStatus"}],"abstract":[{"text":"The Authenticator status","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"status"}],"kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/status"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel/type":{"kind":"symbol","title":"type","abstract":[{"text":"The Authenticator type","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"text":"AuthenticatorType","preciseIdentifier":"s:10PingOneSDK18AuthenticatorModelC0D4TypeO","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/type","url":"\/documentation\/pingonesdk\/authenticatormodel\/type","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"url":"\/documentation\/pingonesdk","type":"topic","kind":"symbol","role":"collection","title":"PingOneSDK"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel/AuthenticatorStatus":{"kind":"symbol","title":"AuthenticatorModel.AuthenticatorStatus","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticatorStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticatorStatus"}],"url":"\/documentation\/pingonesdk\/authenticatormodel\/authenticatorstatus","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/AuthenticatorStatus","type":"topic","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel/AuthenticatorType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticatorType"}],"title":"AuthenticatorModel.AuthenticatorType","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/AuthenticatorType","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticatorType"}],"role":"symbol","kind":"symbol","url":"\/documentation\/pingonesdk\/authenticatormodel\/authenticatortype"},"doc://com.pingIdentity.PingOneSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel/errorMessage":{"kind":"symbol","title":"errorMessage","abstract":[{"text":"Error code in case of authorization method failure","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorMessage","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"errorMessage"}],"url":"\/documentation\/pingonesdk\/authenticatormodel\/errormessage","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/errorMessage","type":"topic","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"AuthenticatorModel","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AuthenticatorModel","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AuthenticatorModel"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/errorCode","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/errorMessage","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/status","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/type"],"title":"Instance Properties"}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"AuthenticatorModel","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"errorCode","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel~1errorCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"errorCode"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel~1errorCode\/fragments"},{"value":"AuthenticatorModel","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/fragments","value":[{"kind":"identifier","text":"AuthenticatorModel"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel~1status\/title","op":"replace","value":"status"},{"op":"replace","value":[{"text":"status","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel~1status\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel~1errorMessage\/title","value":"errorMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel~1errorMessage\/fragments","value":[{"kind":"identifier","text":"errorMessage"}]}]}]}