{"sections":[],"variants":[{"paths":["\/documentation\/pingonesdk\/errorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/errorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"externalID":"c:@M@PingOneSDK@E@ErrorCode","title":"ErrorCode","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ErrorCode","kind":"identifier"}],"roleHeading":"Enumeration","role":"symbol"},"topicSections":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/authCanceled","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/authCodeInvalid","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/bundleId","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/cantUpdateRegion","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/configureError","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/deviceIsNotPaired","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/deviceTokenIsMissing","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/failedPolicyRequirements","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/internalError","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/migrationAlreadyRunning","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/migrationNotNeeded","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/noConnectivity","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pairingAlreadyRunning","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pairingKey","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/passcodeNotValid","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pushConfirmationTimeout","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/serverError","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/testPushAlreadyRunning","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/trustFailed","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/unrecognizedRemoteNotification"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/Equatable-Implementations","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK"]]},"abstract":[{"text":"PingOne SDK error codes.","type":"text"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/SQ","doc:\/\/com.pingIdentity.PingOneSDK\/SH","doc:\/\/com.pingIdentity.PingOneSDK\/SY"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ErrorCode","kind":"identifier"}],"platforms":["iOS"]}]},{"content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"table","header":"row","rows":[[[{"type":"paragraph","inlineContent":[{"text":"Error Code","type":"text"}]}],[{"inlineContent":[{"type":"text","text":"Value"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"internalError"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"10000"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"deviceTokenIsMissing"}]}],[{"inlineContent":[{"text":"10001","type":"text"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"unrecognizedRemoteNotification"}]}],[{"inlineContent":[{"type":"text","text":"10002"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"serverError"}]}],[{"inlineContent":[{"type":"text","text":"10003"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"code":"noConnectivity","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"text":"10004","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"pairingKey"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"10005"}]}]],[[{"inlineContent":[{"code":"bundleId","type":"codeVoice"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"10006","type":"text"}]}]],[[{"inlineContent":[{"type":"codeVoice","code":"deviceIsNotPaired"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"10008"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"pushConfirmationTimeout"}]}],[{"type":"paragraph","inlineContent":[{"text":"10009","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"code":"passcodeNotValid","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"text":"10010","type":"text"}]}]],[[{"inlineContent":[{"code":"authCodeInvalid","type":"codeVoice"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"10011"}]}]],[[{"type":"paragraph","inlineContent":[{"code":"failedPolicyRequirements","type":"codeVoice"}]}],[{"inlineContent":[{"text":"10012","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":"pairingAlreadyRunning"}],"type":"paragraph"}],[{"inlineContent":[{"text":"10013","type":"text"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"code":"migrationAlreadyRunning","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"10014"}]}]],[[{"inlineContent":[{"type":"codeVoice","code":"migrationNotNeeded"}],"type":"paragraph"}],[{"inlineContent":[{"text":"10015","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":"testPushAlreadyRunning"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"10016"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"code":"trustFailed","type":"codeVoice"}]}],[{"inlineContent":[{"type":"text","text":"10017"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"code":"configureError","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"text":"10018","type":"text"}]}]],[[{"inlineContent":[{"type":"codeVoice","code":"cantUpdateRegion"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"10019"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":"authCanceled    ","type":"codeVoice"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"10020","type":"text"}]}]]]}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/pairingKey":{"role":"symbol","navigatorTitle":[{"text":"ErrorCodePairingKey","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pairingKey","kind":"identifier"}],"abstract":[{"type":"text","text":"There was a problem with the pairing key."}],"title":"ErrorCode.pairingKey","type":"topic","url":"\/documentation\/pingonesdk\/errorcode\/pairingkey","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pairingKey"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/migrationNotNeeded":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/migrationNotNeeded","abstract":[{"type":"text","text":"The device does not need to be migrated because it is already paired."}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"migrationNotNeeded"}],"title":"ErrorCode.migrationNotNeeded","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeMigrationNotNeeded"}],"url":"\/documentation\/pingonesdk\/errorcode\/migrationnotneeded"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/failedPolicyRequirements":{"title":"ErrorCode.failedPolicyRequirements","navigatorTitle":[{"text":"ErrorCodeFailedPolicyRequirements","kind":"identifier"}],"abstract":[{"type":"text","text":"Mobile device does not comply with policy requirements."}],"type":"topic","url":"\/documentation\/pingonesdk\/errorcode\/failedpolicyrequirements","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedPolicyRequirements"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/failedPolicyRequirements"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/init(rawValue:)":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/init(rawValue:)","role":"symbol","title":"init(rawValue:)","type":"topic","abstract":[],"url":"\/documentation\/pingonesdk\/errorcode\/init(rawvalue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"abstract":[{"text":"PingOne SDK error codes.","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/errorcode"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/Equatable-Implementations":{"kind":"article","url":"\/documentation\/pingonesdk\/errorcode\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/Equatable-Implementations","type":"topic","abstract":[],"title":"Equatable Implementations"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/unrecognizedRemoteNotification":{"abstract":[{"type":"text","text":"Remote notification isn’t from PingOne."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/unrecognizedRemoteNotification","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unrecognizedRemoteNotification"}],"title":"ErrorCode.unrecognizedRemoteNotification","kind":"symbol","navigatorTitle":[{"text":"ErrorCodeUnrecognizedRemoteNotification","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/errorcode\/unrecognizedremotenotification"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/serverError":{"navigatorTitle":[{"text":"ErrorCodeServerError","kind":"identifier"}],"title":"ErrorCode.serverError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serverError","kind":"identifier"}],"abstract":[{"type":"text","text":"There was a server error."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/serverError","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/errorcode\/servererror"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/pairingAlreadyRunning":{"abstract":[{"type":"text","text":"Pairing is currently in progress - you cannot make another API call until it is completed."}],"url":"\/documentation\/pingonesdk\/errorcode\/pairingalreadyrunning","title":"ErrorCode.pairingAlreadyRunning","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"pairingAlreadyRunning","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodePairingAlreadyRunning","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pairingAlreadyRunning"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/authCanceled":{"abstract":[{"type":"text","text":"The authentication was canceled, approval or denial is not possible."}],"url":"\/documentation\/pingonesdk\/errorcode\/authcanceled","title":"ErrorCode.authCanceled","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"authCanceled","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeAuthCanceled","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/authCanceled"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/bundleId":{"abstract":[{"text":"There was a problem with the bundle id.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"bundleId","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeBundleId"}],"url":"\/documentation\/pingonesdk\/errorcode\/bundleid","type":"topic","role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/bundleId","title":"ErrorCode.bundleId","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/RawRepresentable-Implementations","abstract":[],"url":"\/documentation\/pingonesdk\/errorcode\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/deviceTokenIsMissing":{"abstract":[{"text":"Device token was missing and is required to complete this action.","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/deviceTokenIsMissing","url":"\/documentation\/pingonesdk\/errorcode\/devicetokenismissing","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceTokenIsMissing","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeDeviceTokenIsMissing","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"ErrorCode.deviceTokenIsMissing"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/passcodeNotValid":{"title":"ErrorCode.passcodeNotValid","url":"\/documentation\/pingonesdk\/errorcode\/passcodenotvalid","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"passcodeNotValid","kind":"identifier"}],"abstract":[{"text":"Client failed to verify due to invalid one time passcode sent to the server.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"ErrorCodePasscodeNotValid","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/passcodeNotValid","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/trustFailed":{"kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/trustFailed","abstract":[{"type":"text","text":"The client failed to establish trust with the server."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trustFailed"}],"navigatorTitle":[{"text":"ErrorCodeTrustFailed","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/errorcode\/trustfailed","title":"ErrorCode.trustFailed","type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/cantUpdateRegion":{"navigatorTitle":[{"text":"ErrorCodeCantUpdateRegion","kind":"identifier"}],"title":"ErrorCode.cantUpdateRegion","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cantUpdateRegion","kind":"identifier"}],"abstract":[{"type":"text","text":"The device is already trusted with a certain region and cannot set a new one using configure(PingOneRegion). If needed to change the region, the device should be reset by calling the removePingOneLocalData() method."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/cantUpdateRegion","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/errorcode\/cantupdateregion"},"doc://com.pingIdentity.PingOneSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SH","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/testPushAlreadyRunning":{"title":"ErrorCode.testPushAlreadyRunning","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeTestPushAlreadyRunning"}],"abstract":[{"text":"Test remote notification is currently in progress - you cannot make another API call until it is completed.","type":"text"}],"type":"topic","url":"\/documentation\/pingonesdk\/errorcode\/testpushalreadyrunning","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"testPushAlreadyRunning"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/testPushAlreadyRunning"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/configureError":{"abstract":[{"text":"The SDK was not configured. Make sure to run the configure(PingOneRegion) method first.","type":"text"}],"url":"\/documentation\/pingonesdk\/errorcode\/configureerror","title":"ErrorCode.configureError","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"configureError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeConfigureError"}],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/configureError"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/deviceIsNotPaired":{"title":"ErrorCode.deviceIsNotPaired","abstract":[{"text":"Device is not paired.","type":"text"}],"url":"\/documentation\/pingonesdk\/errorcode\/deviceisnotpaired","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deviceIsNotPaired"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/deviceIsNotPaired","kind":"symbol","navigatorTitle":[{"text":"ErrorCodeDeviceIsNotPaired","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/internalError":{"title":"ErrorCode.internalError","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeInternalError"}],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/internalError","url":"\/documentation\/pingonesdk\/errorcode\/internalerror","kind":"symbol","abstract":[{"type":"text","text":"Internal Error."}]},"doc://com.pingIdentity.PingOneSDK/SY":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/noConnectivity":{"abstract":[{"type":"text","text":"There was a problem with the network."}],"url":"\/documentation\/pingonesdk\/errorcode\/noconnectivity","title":"ErrorCode.noConnectivity","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"noConnectivity"}],"navigatorTitle":[{"text":"ErrorCodeNoConnectivity","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/noConnectivity"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/migrationAlreadyRunning":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeMigrationAlreadyRunning"}],"title":"ErrorCode.migrationAlreadyRunning","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/migrationAlreadyRunning","url":"\/documentation\/pingonesdk\/errorcode\/migrationalreadyrunning","kind":"symbol","abstract":[{"text":"Migration is currently in progress - you cannot make another API call until it is completed.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"migrationAlreadyRunning","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/authCodeInvalid":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeAuthCodeInvalid"}],"title":"ErrorCode.authCodeInvalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authCodeInvalid"}],"abstract":[{"text":"Authentication code is not valid.","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/authCodeInvalid","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/errorcode\/authcodeinvalid"},"doc://com.pingIdentity.PingOneSDK/SQ":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/pushConfirmationTimeout":{"abstract":[{"text":"Client confirmation delay responding to push notification, resulted in timeout.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ErrorCodePushConfirmationTimeout","kind":"identifier"}],"title":"ErrorCode.pushConfirmationTimeout","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushConfirmationTimeout"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pushConfirmationTimeout","url":"\/documentation\/pingonesdk\/errorcode\/pushconfirmationtimeout","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"ErrorCode","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"value":[{"kind":"identifier","text":"ErrorCode"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ErrorCode","kind":"identifier"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/authCanceled","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/authCodeInvalid","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/bundleId","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/cantUpdateRegion","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/configureError","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/deviceIsNotPaired","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/deviceTokenIsMissing","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/failedPolicyRequirements","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/internalError","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/migrationAlreadyRunning","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/migrationNotNeeded","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/noConnectivity","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pairingAlreadyRunning","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pairingKey","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/passcodeNotValid","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pushConfirmationTimeout","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/serverError","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/testPushAlreadyRunning","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/trustFailed","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/unrecognizedRemoteNotification"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ErrorCode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1pairingKey\/title","value":"ErrorCodePairingKey","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCodePairingKey"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1pairingKey\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1migrationNotNeeded\/title","value":"ErrorCodeMigrationNotNeeded","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1migrationNotNeeded\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeMigrationNotNeeded"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1failedPolicyRequirements\/title","op":"replace","value":"ErrorCodeFailedPolicyRequirements"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCodeFailedPolicyRequirements"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1failedPolicyRequirements\/fragments"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title"},{"value":[{"kind":"identifier","text":"ErrorCode"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","op":"replace"},{"value":"ErrorCodeUnrecognizedRemoteNotification","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1unrecognizedRemoteNotification\/title"},{"value":[{"text":"ErrorCodeUnrecognizedRemoteNotification","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1unrecognizedRemoteNotification\/fragments"},{"value":"ErrorCodeServerError","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1serverError\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1serverError\/fragments","value":[{"text":"ErrorCodeServerError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1pairingAlreadyRunning\/title","value":"ErrorCodePairingAlreadyRunning","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1pairingAlreadyRunning\/fragments","value":[{"kind":"identifier","text":"ErrorCodePairingAlreadyRunning"}]},{"value":"ErrorCodeAuthCanceled","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1authCanceled\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1authCanceled\/fragments","value":[{"text":"ErrorCodeAuthCanceled","kind":"identifier"}]},{"op":"replace","value":"ErrorCodeBundleId","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1bundleId\/title"},{"op":"replace","value":[{"text":"ErrorCodeBundleId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1bundleId\/fragments"},{"value":"ErrorCodeDeviceTokenIsMissing","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1deviceTokenIsMissing\/title"},{"op":"replace","value":[{"text":"ErrorCodeDeviceTokenIsMissing","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1deviceTokenIsMissing\/fragments"},{"value":"ErrorCodePasscodeNotValid","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1passcodeNotValid\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1passcodeNotValid\/fragments","value":[{"text":"ErrorCodePasscodeNotValid","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1trustFailed\/title","op":"replace","value":"ErrorCodeTrustFailed"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1trustFailed\/fragments","op":"replace","value":[{"text":"ErrorCodeTrustFailed","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1cantUpdateRegion\/title","value":"ErrorCodeCantUpdateRegion","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1cantUpdateRegion\/fragments","value":[{"text":"ErrorCodeCantUpdateRegion","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1testPushAlreadyRunning\/title","value":"ErrorCodeTestPushAlreadyRunning","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCodeTestPushAlreadyRunning"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1testPushAlreadyRunning\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1configureError\/title","value":"ErrorCodeConfigureError"},{"op":"replace","value":[{"text":"ErrorCodeConfigureError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1configureError\/fragments"},{"value":"ErrorCodeDeviceIsNotPaired","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1deviceIsNotPaired\/title"},{"value":[{"kind":"identifier","text":"ErrorCodeDeviceIsNotPaired"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1deviceIsNotPaired\/fragments"},{"value":"ErrorCodeInternalError","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1internalError\/title","op":"replace"},{"op":"replace","value":[{"text":"ErrorCodeInternalError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1internalError\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1noConnectivity\/title","value":"ErrorCodeNoConnectivity","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1noConnectivity\/fragments","value":[{"kind":"identifier","text":"ErrorCodeNoConnectivity"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1migrationAlreadyRunning\/title","value":"ErrorCodeMigrationAlreadyRunning","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1migrationAlreadyRunning\/fragments","value":[{"kind":"identifier","text":"ErrorCodeMigrationAlreadyRunning"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1authCodeInvalid\/title","value":"ErrorCodeAuthCodeInvalid","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1authCodeInvalid\/fragments","value":[{"text":"ErrorCodeAuthCodeInvalid","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1pushConfirmationTimeout\/title","op":"replace","value":"ErrorCodePushConfirmationTimeout"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1pushConfirmationTimeout\/fragments","value":[{"text":"ErrorCodePushConfirmationTimeout","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}