{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/done","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/failed","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/inProgress","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/notNeeded","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/temporaryFailed"]},{"title":"Initializers","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/Equatable-Implementations","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/RawRepresentable-Implementations"]}],"abstract":[{"type":"text","text":"Enum that represents the migration status returned from the SDK"}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/SQ","doc:\/\/com.pingIdentity.PingOneSDK\/SH","doc:\/\/com.pingIdentity.PingOneSDK\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MigrationStatus"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/pingonesdk\/migrationstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/migrationstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MigrationStatus","kind":"identifier"}],"externalID":"c:@M@PingOneSDK@E@MigrationStatus","symbolKind":"enum","modules":[{"name":"PingOneSDK"}],"title":"MigrationStatus","roleHeading":"Enumeration","role":"symbol","navigatorTitle":[{"text":"MigrationStatus","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","url":"\/documentation\/pingonesdk\/migrationstatus\/rawrepresentable-implementations","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus/failed":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"role":"symbol","type":"topic","title":"MigrationStatus.failed","navigatorTitle":[{"text":"MigrationStatusFailed","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/failed","abstract":[{"type":"text","text":"Migration failed."}],"url":"\/documentation\/pingonesdk\/migrationstatus\/failed"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus/inProgress":{"role":"symbol","url":"\/documentation\/pingonesdk\/migrationstatus\/inprogress","title":"MigrationStatus.inProgress","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"inProgress"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/inProgress","type":"topic","kind":"symbol","abstract":[{"text":"Migration in progress.","type":"text"}],"navigatorTitle":[{"text":"MigrationStatusInProgress","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"url":"\/documentation\/pingonesdk","type":"topic","kind":"symbol","role":"collection","title":"PingOneSDK"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus/done":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/done","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"done","kind":"identifier"}],"title":"MigrationStatus.done","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MigrationStatusDone"}],"url":"\/documentation\/pingonesdk\/migrationstatus\/done","abstract":[{"text":"Migration completed.","type":"text"}]},"doc://com.pingIdentity.PingOneSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SH","title":"Swift.Hashable"},"doc://com.pingIdentity.PingOneSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SQ","title":"Swift.Equatable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus/temporaryFailed":{"title":"MigrationStatus.temporaryFailed","type":"topic","role":"symbol","url":"\/documentation\/pingonesdk\/migrationstatus\/temporaryfailed","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"temporaryFailed"}],"abstract":[{"type":"text","text":"Migration failed due to server error, client can try again."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/temporaryFailed","navigatorTitle":[{"text":"MigrationStatusTemporaryFailed","kind":"identifier"}],"kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus/init(rawValue:)":{"abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":")"}],"url":"\/documentation\/pingonesdk\/migrationstatus\/init(rawvalue:)","title":"init(rawValue:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/init(rawValue:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus/Equatable-Implementations":{"type":"topic","abstract":[],"url":"\/documentation\/pingonesdk\/migrationstatus\/equatable-implementations","kind":"article","title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/Equatable-Implementations"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus":{"type":"topic","abstract":[{"text":"Enum that represents the migration status returned from the SDK","type":"text"}],"kind":"symbol","url":"\/documentation\/pingonesdk\/migrationstatus","navigatorTitle":[{"text":"MigrationStatus","kind":"identifier"}],"title":"MigrationStatus","role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MigrationStatus","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus/notNeeded":{"role":"symbol","url":"\/documentation\/pingonesdk\/migrationstatus\/notneeded","title":"MigrationStatus.notNeeded","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"notNeeded"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/notNeeded","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"There is no PingID data that has to be migrated."}],"navigatorTitle":[{"text":"MigrationStatusNotNeeded","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MigrationStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MigrationStatus"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MigrationStatus","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/done","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/failed","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/inProgress","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/notNeeded","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/temporaryFailed"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MigrationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"MigrationStatusFailed","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1failed\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1failed\/fragments","op":"replace","value":[{"text":"MigrationStatusFailed","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1inProgress\/title","value":"MigrationStatusInProgress"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1inProgress\/fragments","value":[{"text":"MigrationStatusInProgress","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1done\/title","value":"MigrationStatusDone","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1done\/fragments","value":[{"text":"MigrationStatusDone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1temporaryFailed\/title","op":"replace","value":"MigrationStatusTemporaryFailed"},{"value":[{"text":"MigrationStatusTemporaryFailed","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1temporaryFailed\/fragments","op":"replace"},{"value":"MigrationStatus","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus\/title"},{"value":[{"text":"MigrationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus\/fragments","op":"replace"},{"op":"replace","value":"MigrationStatusNotNeeded","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1notNeeded\/title"},{"value":[{"text":"MigrationStatusNotNeeded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1notNeeded\/fragments"}]}]}