{"kind":"symbol","sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/SQ","doc:\/\/com.pingIdentity.PingOneSDK\/SH"],"kind":"relationships"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"NotificationObject"}],"roleHeading":"Class","role":"symbol","modules":[{"name":"PingOneSDK"}],"symbolKind":"class","title":"NotificationObject","externalID":"c:@M@PingOneSDK@objc(cs)NotificationObject","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationObject"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/clientContext","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/notificationType-swift.property","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/numberMatchingOptions","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/numberMatchingType","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/timeoutDuration"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/approve(completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/approve(withAuthenticationMethod:numberMatchingPickedValue:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/deny(completionHandler:)"]},{"title":"Enumerations","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum"]}],"abstract":[{"text":"A Notification Object represents an authentication request via remote notification. It can be approved or denied.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/notificationobject"]},{"paths":["\/documentation\/pingonesdk\/notificationobject"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationObject"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject"},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationObject"}],"type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","role":"symbol","url":"\/documentation\/pingonesdk\/notificationobject","abstract":[{"type":"text","text":"A Notification Object represents an authentication request via remote notification. It can be approved or denied."}],"title":"NotificationObject","navigatorTitle":[{"text":"NotificationObject","kind":"identifier"}],"kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SH","title":"Swift.Hashable"},"doc://com.pingIdentity.PingOneSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","url":"\/documentation\/pingonesdk","role":"collection","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/approve(completionHandler:)":{"deprecated":true,"url":"\/documentation\/pingonesdk\/notificationobject\/approve(completionhandler:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/approve(completionHandler:)","abstract":[{"type":"text","text":"Approve authentication"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"approve"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"approveWithCompletionHandler:"}],"title":"approve(completionHandler:)","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/approve(withAuthenticationMethod:numberMatchingPickedValue:completionHandler:)":{"kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/approve(withAuthenticationMethod:numberMatchingPickedValue:completionHandler:)","title":"approve(withAuthenticationMethod:numberMatchingPickedValue:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"approve"},{"text":"(","kind":"text"},{"text":"withAuthenticationMethod","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"numberMatchingPickedValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"approveWithAuthenticationMethod:numberMatchingPickedValue:completionHandler:","kind":"identifier"}],"abstract":[{"text":"Approve authentication","type":"text"}],"url":"\/documentation\/pingonesdk\/notificationobject\/approve(withauthenticationmethod:numbermatchingpickedvalue:completionhandler:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/deny(completionHandler:)":{"title":"deny(completionHandler:)","url":"\/documentation\/pingonesdk\/notificationobject\/deny(completionhandler:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deny","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"denyWithCompletionHandler:","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/deny(completionHandler:)","abstract":[{"type":"text","text":"Deny authentication"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/notificationType-swift.property":{"url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.property","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/notificationType-swift.property","abstract":[{"type":"text","text":"Describes the purpose of the notification."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"notificationType","kind":"identifier"},{"kind":"text","text":": "},{"text":"NotificationType","preciseIdentifier":"s:10PingOneSDK18NotificationObjectC0D4TypeO","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"notificationType","kind":"identifier"}],"title":"notificationType","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/SQ":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationType"}],"type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum","role":"symbol","url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum","abstract":[{"type":"text","text":"Type that describes the purpose of the notification."}],"title":"NotificationObject.NotificationType","navigatorTitle":[{"text":"NotificationType","kind":"identifier"}],"kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/clientContext":{"url":"\/documentation\/pingonesdk\/notificationobject\/clientcontext","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/clientContext","abstract":[{"text":"Extra parameters are passed to the client with the push object","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientContext","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"clientContext"}],"title":"clientContext","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/numberMatchingType":{"type":"topic","abstract":[{"text":"Type of number matching. If it is SELECT_NUMBER, the user will pick a number from numberMatchingOptions. If it is ENTER_MANUALLY, the number will be entered manually, and no options will be presented.","type":"text"}],"url":"\/documentation\/pingonesdk\/notificationobject\/numbermatchingtype","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/numberMatchingType","kind":"symbol","navigatorTitle":[{"text":"numberMatchingType","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"numberMatchingType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","title":"numberMatchingType"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/timeoutDuration":{"url":"\/documentation\/pingonesdk\/notificationobject\/timeoutduration","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/timeoutDuration","abstract":[{"type":"text","text":"The maximum time duration allowed from getting push till user response."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"timeoutDuration","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"timeoutDuration","kind":"identifier"}],"title":"timeoutDuration","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/s7CVarArgP":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.pingIdentity.PingOneSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pingIdentity.PingOneSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/numberMatchingOptions":{"navigatorTitle":[{"kind":"identifier","text":"numberMatchingOptions"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/numberMatchingOptions","role":"symbol","title":"numberMatchingOptions","type":"topic","abstract":[{"type":"text","text":"Array of integer options for number matching"}],"url":"\/documentation\/pingonesdk\/notificationobject\/numbermatchingoptions","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberMatchingOptions"},{"text":": [","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":"]"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"NotificationObject","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"NotificationObject"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"NotificationObject"}]},{"value":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/clientContext","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/notificationType-swift.property","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/numberMatchingOptions","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/numberMatchingType","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/timeoutDuration"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/approve(completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/approve(withAuthenticationMethod:numberMatchingPickedValue:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/deny(completionHandler:)"]}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationObject"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"NotificationObject","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/title","op":"replace"},{"value":[{"text":"NotificationObject","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1approve(completionHandler:)\/title","value":"approveWithCompletionHandler:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1approve(completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"approveWithCompletionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1approve(withAuthenticationMethod:numberMatchingPickedValue:completionHandler:)\/title","value":"approveWithAuthenticationMethod:numberMatchingPickedValue:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1approve(withAuthenticationMethod:numberMatchingPickedValue:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"approveWithAuthenticationMethod:numberMatchingPickedValue:completionHandler:"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1deny(completionHandler:)\/title","op":"replace","value":"denyWithCompletionHandler:"},{"value":[{"text":"- ","kind":"text"},{"text":"denyWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1deny(completionHandler:)\/fragments"},{"op":"replace","value":"notificationType","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1notificationType-swift.property\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1notificationType-swift.property\/fragments","value":[{"kind":"identifier","text":"notificationType"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1clientContext\/title","op":"replace","value":"clientContext"},{"value":[{"text":"clientContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1clientContext\/fragments"},{"op":"replace","value":"numberMatchingType","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1numberMatchingType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1numberMatchingType\/fragments","value":[{"kind":"identifier","text":"numberMatchingType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1timeoutDuration\/title","value":"timeoutDuration"},{"value":[{"text":"timeoutDuration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1timeoutDuration\/fragments"},{"op":"replace","value":"numberMatchingOptions","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1numberMatchingOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1numberMatchingOptions\/fragments","value":[{"kind":"identifier","text":"numberMatchingOptions"}]}]}]}