{"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject\/approve(completion:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject\/approve(completionHandler:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PairingObject"}]}]}],"sections":[],"metadata":{"modules":[{"name":"PingOneSDK"}],"title":"PairingObject","roleHeading":"Class","externalID":"c:@M@PingOneSDK@objc(cs)PairingObject","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PairingObject","kind":"identifier"}],"symbolKind":"class","navigatorTitle":[{"text":"PairingObject","kind":"identifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"PairingObject represents a pairing request that can be approved or ignored."}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/SQ","doc:\/\/com.pingIdentity.PingOneSDK\/SH"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pairingobject"]},{"paths":["\/documentation\/pingonesdk\/pairingobject"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK"]]},"references":{"doc://com.pingIdentity.PingOneSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PairingObject/approve(completion:)":{"navigatorTitle":[{"kind":"identifier","text":"approveWithCompletion:"}],"title":"approve(completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"approve","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"response","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PingOneSDK@objc(cs)PairingInfo","text":"PairingInfo","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Approve pairing"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject\/approve(completion:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pingonesdk\/pairingobject\/approve(completion:)"},"doc://com.pingIdentity.PingOneSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.pingIdentity.PingOneSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PairingObject/approve(completionHandler:)":{"url":"\/documentation\/pingonesdk\/pairingobject\/approve(completionhandler:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"approve","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"approveWithCompletionHandler:"}],"deprecated":true,"kind":"symbol","title":"approve(completionHandler:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject\/approve(completionHandler:)","type":"topic","abstract":[{"type":"text","text":"Approve pairing"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PairingObject":{"url":"\/documentation\/pingonesdk\/pairingobject","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PairingObject"}],"navigatorTitle":[{"kind":"identifier","text":"PairingObject"}],"title":"PairingObject","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"PairingObject represents a pairing request that can be approved or ignored."}]},"doc://com.pingIdentity.PingOneSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.pingIdentity.PingOneSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SH","title":"Swift.Hashable"},"doc://com.pingIdentity.PingOneSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.pingIdentity.PingOneSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PairingObject","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"PairingObject","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"PairingObject"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject\/approve(completion:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject\/approve(completionHandler:)"]}]},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"PairingObject","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingObject~1approve(completion:)\/title","value":"approveWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingObject~1approve(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"approveWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingObject~1approve(completionHandler:)\/title","value":"approveWithCompletionHandler:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"approveWithCompletionHandler:"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingObject~1approve(completionHandler:)\/fragments"},{"value":"PairingObject","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingObject\/title"},{"value":[{"text":"PairingObject","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingObject\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}