{"relationshipsSections":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/SQ","doc:\/\/com.pingIdentity.PingOneSDK\/SH"]}],"metadata":{"role":"symbol","externalID":"c:@M@PingOneSDK@objc(cs)PairingInfo","symbolKind":"class","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PairingInfo","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PairingInfo"}],"title":"PairingInfo","modules":[{"name":"PingOneSDK"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PairingInfo","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pairinginfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pairinginfo"]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK"]]},"abstract":[{"type":"text","text":"Public PairingInfo class contains data about pairing resolution"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo\/authenticatorsArray"],"title":"Instance Properties"}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PairingInfo/authenticatorsArray":{"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo\/authenticatorsArray","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"authenticatorsArray","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@PingOneSDK@objc(cs)AuthenticatorModel","text":"AuthenticatorModel","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"authenticatorsArray"}],"url":"\/documentation\/pingonesdk\/pairinginfo\/authenticatorsarray","type":"topic","title":"authenticatorsArray","abstract":[{"text":"List of authentication methods and their statuses","type":"text"}],"kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PairingInfo":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PairingInfo"}],"url":"\/documentation\/pingonesdk\/pairinginfo","abstract":[{"text":"Public PairingInfo class contains data about pairing resolution","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PairingInfo","kind":"identifier"}],"title":"PairingInfo"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"url":"\/documentation\/pingonesdk","type":"topic","kind":"symbol","role":"collection","title":"PingOneSDK"},"doc://com.pingIdentity.PingOneSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SQ","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SH","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"PairingInfo","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PairingInfo","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PairingInfo"}]},{"value":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo\/authenticatorsArray"],"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PairingInfo"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"authenticatorsArray","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingInfo~1authenticatorsArray\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingInfo~1authenticatorsArray\/fragments","op":"replace","value":[{"kind":"identifier","text":"authenticatorsArray"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingInfo\/title","value":"PairingInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingInfo\/fragments","value":[{"text":"PairingInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}