{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"symbolKind":"enum","role":"symbol","externalID":"c:@M@PingOneSDK@E@PingOneRegion","navigatorTitle":[{"text":"PingOneRegion","kind":"identifier"}],"title":"PingOneRegion","modules":[{"name":"PingOneSDK"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneRegion"}],"roleHeading":"Enumeration"},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/Se","doc:\/\/com.pingIdentity.PingOneSDK\/SE","doc:\/\/com.pingIdentity.PingOneSDK\/SQ","doc:\/\/com.pingIdentity.PingOneSDK\/SH","doc:\/\/com.pingIdentity.PingOneSDK\/SY"],"type":"conformsTo","kind":"relationships"}],"abstract":[{"type":"text","text":"Public enum that describes the regions available for PingOne SDK."}],"kind":"symbol","variants":[{"paths":["\/documentation\/pingonesdk\/pingoneregion"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pingoneregion"]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Australia","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/AustraliaCom","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Canada","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Europe","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/NorthAmerica"]},{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/stringName()"],"title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Equatable-Implementations","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneRegion"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK"]]},"references":{"doc://com.pingIdentity.PingOneSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SQ"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneRegion"}],"title":"PingOneRegion","abstract":[{"text":"Public enum that describes the regions available for PingOne SDK.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"PingOneRegion","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion","url":"\/documentation\/pingonesdk\/pingoneregion","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion/Equatable-Implementations":{"kind":"article","type":"topic","abstract":[],"url":"\/documentation\/pingonesdk\/pingoneregion\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","url":"\/documentation\/pingonesdk","role":"collection","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/Se"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion/Europe":{"navigatorTitle":[{"text":"PingOneRegionEurope","kind":"identifier"}],"title":"PingOneRegion.Europe","kind":"symbol","abstract":[{"type":"text","text":"Europe"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Europe","url":"\/documentation\/pingonesdk\/pingoneregion\/europe","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Europe"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion/AustraliaCom":{"navigatorTitle":[{"text":"PingOneRegionAustraliaCom","kind":"identifier"}],"kind":"symbol","title":"PingOneRegion.AustraliaCom","abstract":[{"text":"Australia Com","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/AustraliaCom","url":"\/documentation\/pingonesdk\/pingoneregion\/australiacom","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AustraliaCom"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion/Canada":{"title":"PingOneRegion.Canada","navigatorTitle":[{"text":"PingOneRegionCanada","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"Canada","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Canada","abstract":[{"text":"Canada","type":"text"}],"url":"\/documentation\/pingonesdk\/pingoneregion\/canada"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion/stringName()":{"title":"stringName()","kind":"symbol","abstract":[{"type":"text","text":"Fetch the Region enum name"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/stringName()","url":"\/documentation\/pingonesdk\/pingoneregion\/stringname()","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringName"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion/NorthAmerica":{"navigatorTitle":[{"kind":"identifier","text":"PingOneRegionNorthAmerica"}],"kind":"symbol","title":"PingOneRegion.NorthAmerica","abstract":[{"type":"text","text":"North America"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/NorthAmerica","url":"\/documentation\/pingonesdk\/pingoneregion\/northamerica","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NorthAmerica"}]},"doc://com.pingIdentity.PingOneSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SE"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion/init(rawValue:)":{"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/init(rawValue:)","type":"topic","title":"init(rawValue:)","kind":"symbol","url":"\/documentation\/pingonesdk\/pingoneregion\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":")","kind":"text"}],"abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion/Australia":{"url":"\/documentation\/pingonesdk\/pingoneregion\/australia","abstract":[{"text":"Australia","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PingOneRegionAustralia"}],"title":"PingOneRegion.Australia","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Australia","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Australia"}]},"doc://com.pingIdentity.PingOneSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SH"},"doc://com.pingIdentity.PingOneSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SY"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"type":"topic","kind":"article","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/RawRepresentable-Implementations","url":"\/documentation\/pingonesdk\/pingoneregion\/rawrepresentable-implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"PingOneRegion","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PingOneRegion"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PingOneRegion"}]},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Australia","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/AustraliaCom","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Canada","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Europe","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/NorthAmerica"]}],"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneRegion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"PingOneRegion","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/fragments","value":[{"kind":"identifier","text":"PingOneRegion"}]},{"op":"replace","value":"PingOneRegionEurope","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1Europe\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1Europe\/fragments","value":[{"text":"PingOneRegionEurope","kind":"identifier"}]},{"value":"PingOneRegionAustraliaCom","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1AustraliaCom\/title"},{"op":"replace","value":[{"text":"PingOneRegionAustraliaCom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1AustraliaCom\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1Canada\/title","value":"PingOneRegionCanada"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1Canada\/fragments","value":[{"text":"PingOneRegionCanada","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1NorthAmerica\/title","op":"replace","value":"PingOneRegionNorthAmerica"},{"value":[{"kind":"identifier","text":"PingOneRegionNorthAmerica"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1NorthAmerica\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1Australia\/title","op":"replace","value":"PingOneRegionAustralia"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1Australia\/fragments","op":"replace","value":[{"text":"PingOneRegionAustralia","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}