{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"notificationType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NotificationType","preciseIdentifier":"s:10PingOneSDK18NotificationObjectC0D4TypeO","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"PingOneSDK"}],"externalID":"c:@M@PingOneSDK@objc(cs)NotificationObject(py)notificationType","role":"symbol","title":"notificationType","symbolKind":"property","navigatorTitle":[{"text":"notificationType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notificationType"},{"text":": ","kind":"text"},{"text":"NotificationType","kind":"typeIdentifier","preciseIdentifier":"s:10PingOneSDK18NotificationObjectC0D4TypeO"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Describes the purpose of the notification."}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/notificationType-swift.property","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationType":{"type":"topic","abstract":[{"text":"Type that describes the purpose of the notification.","type":"text"}],"title":"NotificationType","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationType","url":"\/documentation\/pingonesdk\/notificationtype","fragments":[{"kind":"identifier","text":"NotificationType"}],"role":"symbol","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","url":"\/documentation\/pingonesdk","role":"collection","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/notificationType-swift.property":{"url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.property","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/notificationType-swift.property","abstract":[{"type":"text","text":"Describes the purpose of the notification."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"notificationType","kind":"identifier"},{"kind":"text","text":": "},{"text":"NotificationType","preciseIdentifier":"s:10PingOneSDK18NotificationObjectC0D4TypeO","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"notificationType","kind":"identifier"}],"title":"notificationType","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationType"}],"type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum","role":"symbol","url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum","abstract":[{"type":"text","text":"Type that describes the purpose of the notification."}],"title":"NotificationObject.NotificationType","navigatorTitle":[{"text":"NotificationType","kind":"identifier"}],"kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationObject"}],"type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","role":"symbol","url":"\/documentation\/pingonesdk\/notificationobject","abstract":[{"type":"text","text":"A Notification Object represents an authentication request via remote notification. It can be approved or denied."}],"title":"NotificationObject","navigatorTitle":[{"text":"NotificationObject","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"notificationType","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"notificationType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationType","text":"NotificationType","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@E@NotificationType"},{"kind":"text","text":" "},{"text":"notificationType","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1notificationType-swift.property\/title","op":"replace","value":"notificationType"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1notificationType-swift.property\/fragments","value":[{"text":"notificationType","kind":"identifier"}]},{"op":"replace","value":"NotificationObject","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/fragments","value":[{"kind":"identifier","text":"NotificationObject"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}