{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","externalID":"c:@M@PingOneSDK@objc(cs)NotificationObject(py)notificationType","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notificationType"},{"kind":"text","text":": "},{"text":"NotificationType","kind":"typeIdentifier","preciseIdentifier":"s:10PingOneSDK18NotificationObjectC0D4TypeO"}],"navigatorTitle":[{"text":"notificationType","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"PingOneSDK"}],"symbolKind":"property","title":"notificationType"},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject"]]},"abstract":[{"text":"Describes the purpose of the notification.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/notificationType-c.property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/notificationobject\/notificationtype-c.property"]},{"paths":["\/documentation\/pingonesdk\/notificationobject\/notificationtype-c.property"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10PingOneSDK18NotificationObjectC0D4TypeO","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum","text":"NotificationType"}]}]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationType":{"fragments":[{"text":"NotificationType","kind":"identifier"}],"kind":"symbol","type":"topic","title":"NotificationType","abstract":[{"type":"text","text":"Type that describes the purpose of the notification."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationType","role":"symbol","url":"\/documentation\/pingonesdk\/notificationtype"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"url":"\/documentation\/pingonesdk","type":"topic","kind":"symbol","role":"collection","title":"PingOneSDK"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationObject"}],"kind":"symbol","abstract":[{"text":"A Notification Object represents an authentication request via remote notification. It can be approved or denied.","type":"text"}],"type":"topic","title":"NotificationObject","role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","navigatorTitle":[{"kind":"identifier","text":"NotificationObject"}],"url":"\/documentation\/pingonesdk\/notificationobject"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/notificationType-c.property":{"type":"topic","kind":"symbol","title":"notificationType","abstract":[{"text":"Describes the purpose of the notification.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"notificationType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NotificationType","kind":"typeIdentifier","preciseIdentifier":"s:10PingOneSDK18NotificationObjectC0D4TypeO"}],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/notificationType-c.property","navigatorTitle":[{"kind":"identifier","text":"notificationType"}],"url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-c.property"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum":{"url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum","title":"NotificationObject.NotificationType","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationType"}],"abstract":[{"type":"text","text":"Type that describes the purpose of the notification."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NotificationType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"notificationType","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"notificationType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@E@NotificationType","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationType","text":"NotificationType"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"NotificationObject","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/title"},{"value":[{"kind":"identifier","text":"NotificationObject"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/fragments"},{"value":"notificationType","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1notificationType-c.property\/title","op":"replace"},{"value":[{"text":"notificationType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1notificationType-c.property\/fragments","op":"replace"}]}]}