{"metadata":{"title":"numberMatchingType","navigatorTitle":[{"text":"numberMatchingType","kind":"identifier"}],"modules":[{"name":"PingOneSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"numberMatchingType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"c:@M@PingOneSDK@objc(cs)NotificationObject(py)numberMatchingType","symbolKind":"property","roleHeading":"Instance Property","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/notificationobject\/numbermatchingtype"]},{"paths":["\/documentation\/pingonesdk\/notificationobject\/numbermatchingtype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"numberMatchingType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/numberMatchingType","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"text":"Type of number matching. If it is SELECT_NUMBER, the user will pick a number from numberMatchingOptions. If it is ENTER_MANUALLY, the number will be entered manually, and no options will be presented.","type":"text"}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject":{"url":"\/documentation\/pingonesdk\/notificationobject","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationObject","kind":"identifier"}],"title":"NotificationObject","navigatorTitle":[{"kind":"identifier","text":"NotificationObject"}],"abstract":[{"type":"text","text":"A Notification Object represents an authentication request via remote notification. It can be approved or denied."}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/numberMatchingType":{"title":"numberMatchingType","navigatorTitle":[{"kind":"identifier","text":"numberMatchingType"}],"abstract":[{"text":"Type of number matching. If it is SELECT_NUMBER, the user will pick a number from numberMatchingOptions. If it is ENTER_MANUALLY, the number will be entered manually, and no options will be presented.","type":"text"}],"type":"topic","url":"\/documentation\/pingonesdk\/notificationobject\/numbermatchingtype","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"numberMatchingType","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/numberMatchingType"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"numberMatchingType","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"numberMatchingType"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"numberMatchingType","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/title","value":"NotificationObject"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/fragments","value":[{"text":"NotificationObject","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1numberMatchingType\/title","op":"replace","value":"numberMatchingType"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1numberMatchingType\/fragments","value":[{"kind":"identifier","text":"numberMatchingType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}