{"abstract":[{"type":"text","text":"Initializes the PingOne SDK for a specific region."}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"configureWithRegion:completionHandler:","kind":"identifier"}],"modules":[{"name":"PingOneSDK"}],"title":"configure(region:completionHandler:)","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"text":"(","kind":"text"},{"text":"region","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PingOneRegion","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@E@PingOneRegion"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)configureWithRegion:completionHandler:","symbolKind":"method","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configure"},{"text":"(","kind":"text"},{"text":"region","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PingOneSDK@E@PingOneRegion","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion","text":"PingOneRegion","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"region","content":[{"inlineContent":[{"type":"text","text":"The selected enum value."},{"text":" ","type":"text"},{"text":"Possible values are: ","type":"text"},{"code":"NorthAmerica","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"Europe"},{"type":"text","text":", "},{"code":"Canada","type":"codeVoice"},{"text":", ","type":"text"},{"code":"Australia","type":"codeVoice"},{"type":"text","text":", and "},{"code":"AustraliaCom","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}]},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"NSError in case of an error."}]}],"kind":"content"},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"aside","style":"warning","name":"Warning","content":[{"inlineContent":[{"type":"text","text":"If this method is not called, the SDK will initialize with the default"},{"type":"text","text":" "},{"type":"text","text":"North America region."}],"type":"paragraph"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingone\/configure(region:completionhandler:)"]},{"paths":["\/documentation\/pingonesdk\/pingone\/configure(region:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/configure(region:completionHandler:)"},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","url":"\/documentation\/pingonesdk","role":"collection","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PingOne","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","kind":"symbol","url":"\/documentation\/pingonesdk\/pingone","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PingOne"}],"title":"PingOne"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/configure(region:completionHandler:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"configure","kind":"identifier"},{"kind":"text","text":"("},{"text":"region","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PingOneRegion","preciseIdentifier":"c:@M@PingOneSDK@E@PingOneRegion","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"configureWithRegion:completionHandler:","kind":"identifier"}],"role":"symbol","title":"configure(region:completionHandler:)","kind":"symbol","abstract":[{"text":"Initializes the PingOne SDK for a specific region.","type":"text"}],"url":"\/documentation\/pingonesdk\/pingone\/configure(region:completionhandler:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/configure(region:completionHandler:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneRegion"}],"title":"PingOneRegion","abstract":[{"text":"Public enum that describes the regions available for PingOne SDK.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"PingOneRegion","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion","url":"\/documentation\/pingonesdk\/pingoneregion","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"configureWithRegion:completionHandler:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"configureWithRegion:completionHandler:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"configureWithRegion:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@PingOneSDK@E@PingOneRegion","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion","text":"PingOneRegion","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"region","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"PingOne","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments","value":[{"kind":"identifier","text":"PingOne"}],"op":"replace"},{"op":"replace","value":"configureWithRegion:completionHandler:","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1configure(region:completionHandler:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1configure(region:completionHandler:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"configureWithRegion:completionHandler:"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/title","op":"replace","value":"PingOneRegion"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/fragments","value":[{"kind":"identifier","text":"PingOneRegion"}]}]}]}