{"sections":[],"metadata":{"roleHeading":"Type Method","modules":[{"name":"PingOneSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateMobilePayload"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"generateMobilePayloadAndReturnError:","kind":"identifier"}],"title":"generateMobilePayload()","symbolKind":"method","role":"symbol","externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)generateMobilePayloadAndReturnError:"},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"kind":"symbol","abstract":[{"type":"text","text":"Generate a payload string for any communication needed between the customer mobile app and the PingOne server."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generateMobilePayload"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The mobile payload string."}]}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"The PingOne Native SDK returns a native payload to the customer native application."},{"text":" ","type":"text"},{"type":"text","text":"The payload is a small data package created by the PingOne Native SDK component,"},{"type":"text","text":" "},{"type":"text","text":"which is used as part of the device’s authorization."}],"type":"paragraph"},{"type":"aside","style":"note","name":"Throws","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSError if failed to create payload."}]}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/generateMobilePayload()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingone\/generatemobilepayload()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pingone\/generatemobilepayload()"]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"kind":"symbol","navigatorTitle":[{"text":"PingOne","kind":"identifier"}],"abstract":[],"url":"\/documentation\/pingonesdk\/pingone","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PingOne","kind":"identifier"}],"title":"PingOne"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/generateMobilePayload()":{"abstract":[{"type":"text","text":"Generate a payload string for any communication needed between the customer mobile app and the PingOne server."}],"title":"generateMobilePayload()","url":"\/documentation\/pingonesdk\/pingone\/generatemobilepayload()","navigatorTitle":[{"text":"generateMobilePayloadAndReturnError:","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generateMobilePayload"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/generateMobilePayload()","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"url":"\/documentation\/pingonesdk","type":"topic","kind":"symbol","role":"collection","title":"PingOneSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"generateMobilePayloadAndReturnError:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"generateMobilePayloadAndReturnError:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"generateMobilePayloadAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","value":"PingOne"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments","value":[{"kind":"identifier","text":"PingOne"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1generateMobilePayload()\/title","value":"generateMobilePayloadAndReturnError:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1generateMobilePayload()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"generateMobilePayloadAndReturnError:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}