{"variants":[{"paths":["\/documentation\/pingonesdk\/pingone\/getonetimepasscode(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/pingone\/getonetimepasscode(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getOneTimePasscode","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"passcodeInfo","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PingOneSDK@objc(cs)OneTimePasscodeInfo","kind":"typeIdentifier","text":"OneTimePasscodeInfo","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"a completionHandler that contains OneTimePasscodeInfo object."},{"type":"text","text":" "},{"text":"It will contain all the data of the one time passcode if available.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"In case of an error will return NSError."}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Requests the SDK to provide a one time passcode for authentication.","type":"text"}]}]}],"abstract":[{"type":"text","text":"Get one time passcode"}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getOneTimePasscode(_:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Type Method","modules":[{"name":"PingOneSDK"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getOneTimePasscode"},{"text":"((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"passcodeInfo","kind":"internalParam"},{"kind":"text","text":": "},{"text":"OneTimePasscodeInfo","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)OneTimePasscodeInfo","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"getOneTimePasscode:","kind":"identifier"}],"title":"getOneTimePasscode(_:)","externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)getOneTimePasscode:"},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PingOne","kind":"identifier"}],"navigatorTitle":[{"text":"PingOne","kind":"identifier"}],"abstract":[],"title":"PingOne","url":"\/documentation\/pingonesdk\/pingone"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/OneTimePasscodeInfo":{"navigatorTitle":[{"kind":"identifier","text":"OneTimePasscodeInfo"}],"title":"OneTimePasscodeInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OneTimePasscodeInfo"}],"abstract":[{"type":"text","text":"Public class that contains data of the One Time Passcode"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/onetimepasscodeinfo"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/getOneTimePasscode(_:)":{"title":"getOneTimePasscode(_:)","url":"\/documentation\/pingonesdk\/pingone\/getonetimepasscode(_:)","navigatorTitle":[{"kind":"identifier","text":"getOneTimePasscode:"}],"abstract":[{"type":"text","text":"Get one time passcode"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getOneTimePasscode(_:)","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getOneTimePasscode","kind":"identifier"},{"text":"((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"passcodeInfo","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PingOneSDK@objc(cs)OneTimePasscodeInfo","text":"OneTimePasscodeInfo","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getOneTimePasscode:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"getOneTimePasscode:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getOneTimePasscode:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"OneTimePasscodeInfo","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)OneTimePasscodeInfo","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","value":"PingOne","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PingOne"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments"},{"value":"OneTimePasscodeInfo","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo\/fragments","op":"replace","value":[{"text":"OneTimePasscodeInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1getOneTimePasscode(_:)\/title","op":"replace","value":"getOneTimePasscode:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"getOneTimePasscode:"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1getOneTimePasscode(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}