{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Migrate from PingID","type":"text"}],"metadata":{"modules":[{"name":"PingOneSDK"}],"symbolKind":"method","title":"migrateFromPingID(completionHandler:)","roleHeading":"Type Method","externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)migrateFromPingIDWithCompletionHandler:","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"migrateFromPingID","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"status","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MigrationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@E@MigrationStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"kind":"text","text":": "},{"text":"PairingInfo","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)PairingInfo","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"migrateFromPingIDWithCompletionHandler:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/migrateFromPingID(completionHandler:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"migrateFromPingID","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"status","kind":"internalParam"},{"kind":"text","text":": "},{"text":"MigrationStatus","preciseIdentifier":"c:@M@PingOneSDK@E@MigrationStatus","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"response","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PairingInfo","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)PairingInfo","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"a "},{"type":"codeVoice","code":"completionHandler"},{"text":" which contains: ","type":"text"},{"code":"status","type":"codeVoice"},{"text":" - integer that reflects the migration status,","type":"text"},{"text":" ","type":"text"},{"code":"PairingInfo","type":"codeVoice"},{"text":" - an array of the permitted authentication methods - see description of pair method","type":"text"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"code":"error","type":"codeVoice"},{"type":"text","text":" in case of an error will return NSError."}]}],"kind":"content"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"text":"Migrates the PingID SDK application to the PingOne platform","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingone\/migratefrompingid(completionhandler:)"]},{"paths":["\/documentation\/pingonesdk\/pingone\/migratefrompingid(completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PingOne","kind":"identifier"}],"navigatorTitle":[{"text":"PingOne","kind":"identifier"}],"abstract":[],"title":"PingOne","url":"\/documentation\/pingonesdk\/pingone"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus":{"abstract":[{"text":"Enum that represents the migration status returned from the SDK","type":"text"}],"type":"topic","title":"MigrationStatus","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus","url":"\/documentation\/pingonesdk\/migrationstatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MigrationStatus"}],"kind":"symbol","navigatorTitle":[{"text":"MigrationStatus","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/migrateFromPingID(completionHandler:)":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"migrateFromPingID","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@E@MigrationStatus","text":"MigrationStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"response","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PairingInfo","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)PairingInfo"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"migrateFromPingIDWithCompletionHandler:","kind":"identifier"}],"title":"migrateFromPingID(completionHandler:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/migrateFromPingID(completionHandler:)","abstract":[{"type":"text","text":"Migrate from PingID"}],"role":"symbol","type":"topic","url":"\/documentation\/pingonesdk\/pingone\/migratefrompingid(completionhandler:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PairingInfo":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo","navigatorTitle":[{"text":"PairingInfo","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/pairinginfo","role":"symbol","title":"PairingInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PairingInfo"}],"kind":"symbol","abstract":[{"type":"text","text":"Public PairingInfo class contains data about pairing resolution"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"migrateFromPingIDWithCompletionHandler:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"migrateFromPingIDWithCompletionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"migrateFromPingIDWithCompletionHandler:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"MigrationStatus","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus","preciseIdentifier":"c:@M@PingOneSDK@E@MigrationStatus"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"text":"PairingInfo","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)PairingInfo","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","value":"PingOne","op":"replace"},{"value":[{"kind":"identifier","text":"PingOne"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus\/title","value":"MigrationStatus","op":"replace"},{"op":"replace","value":[{"text":"MigrationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1migrateFromPingID(completionHandler:)\/title","value":"migrateFromPingIDWithCompletionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1migrateFromPingID(completionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"migrateFromPingIDWithCompletionHandler:","kind":"identifier"}]},{"value":"PairingInfo","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingInfo\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingInfo\/fragments","value":[{"kind":"identifier","text":"PairingInfo"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}