{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/pair(_:completion:)"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"abstract":[{"type":"text","text":"Pair device"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingone\/pair(_:completion:)"]},{"paths":["\/documentation\/pingonesdk\/pingone\/pair(_:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pair","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pairingKey","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PairingInfo","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)PairingInfo"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"pairingKey","content":[{"inlineContent":[{"text":"pairing key as a string.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"a ","type":"text"},{"type":"codeVoice","code":"completionHandler"},{"type":"text","text":" which contains "},{"code":"PairingInfo","type":"codeVoice"},{"type":"text","text":", a wrapper object that contains an array list with"},{"text":" ","type":"text"},{"text":"authentication methods (One time passcode and Push) status.","type":"text"},{"text":" ","type":"text"},{"text":"In case of error ","type":"text"},{"type":"codeVoice","code":"PairingInfo"},{"text":" will also contain ","type":"text"},{"type":"codeVoice","code":"NSError"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Documentation for pairing object error codes can be found ","type":"text"},{"type":"reference","identifier":"https:\/\/apidocs.pingidentity.com\/pingone\/native-sdks\/v1\/api\/#pingone-mobile-sdk-for-ios","isActive":true}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Pairs the device with the PingOne server using the ","type":"text"},{"code":"pairing key","type":"codeVoice"},{"type":"text","text":"."}]}]}],"metadata":{"navigatorTitle":[{"text":"pair:completion:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pair"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"response"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PingOneSDK@objc(cs)PairingInfo","text":"PairingInfo","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"roleHeading":"Type Method","modules":[{"name":"PingOneSDK"}],"externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)pair:completion:","title":"pair(_:completion:)","symbolKind":"method"},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/pair(_:completion:)":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/pair(_:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pair","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)PairingInfo","text":"PairingInfo"},{"text":"?, ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"pair:completion:"}],"kind":"symbol","abstract":[{"type":"text","text":"Pair device"}],"url":"\/documentation\/pingonesdk\/pingone\/pair(_:completion:)","title":"pair(_:completion:)","type":"topic"},"https://apidocs.pingidentity.com/pingone/native-sdks/v1/api/#pingone-mobile-sdk-for-ios":{"type":"link","titleInlineContent":[{"type":"text","text":"here"}],"url":"https:\/\/apidocs.pingidentity.com\/pingone\/native-sdks\/v1\/api\/#pingone-mobile-sdk-for-ios","title":"here","identifier":"https:\/\/apidocs.pingidentity.com\/pingone\/native-sdks\/v1\/api\/#pingone-mobile-sdk-for-ios"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"kind":"symbol","navigatorTitle":[{"text":"PingOne","kind":"identifier"}],"abstract":[],"url":"\/documentation\/pingonesdk\/pingone","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PingOne","kind":"identifier"}],"title":"PingOne"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"url":"\/documentation\/pingonesdk","type":"topic","kind":"symbol","role":"collection","title":"PingOneSDK"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PairingInfo":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PairingInfo"}],"url":"\/documentation\/pingonesdk\/pairinginfo","abstract":[{"text":"Public PairingInfo class contains data about pairing resolution","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PairingInfo","kind":"identifier"}],"title":"PairingInfo"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"pair:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"pair:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"pair:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"pairingKey","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:@M@PingOneSDK@objc(cs)PairingInfo","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo","kind":"typeIdentifier","text":"PairingInfo"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":", ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"pair:completion:","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1pair(_:completion:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"pair:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1pair(_:completion:)\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","value":"PingOne","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments","value":[{"text":"PingOne","kind":"identifier"}]},{"value":"PairingInfo","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingInfo\/title"},{"value":[{"kind":"identifier","text":"PairingInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingInfo\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}