{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"processRemoteNotificationAction"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"authenticationMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"forRemoteNotification","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"userInfo"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"notificationObject","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationObject","kind":"typeIdentifier","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","text":"NotificationObject"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"completionHandler that will contain NSError in case of an error."},{"text":" ","type":"text"},{"text":"NotificationObject will be returned in case an action is required.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Tells PingOne server to perform the custom action specified by a remote notification. Should be within userNotificationCenter(_:didReceive:withCompletionHandler:) method."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"identifier: The "},{"code":"String","type":"codeVoice"},{"type":"text","text":" is the response.actionIdentifier received within userNotificationCenter(_:didReceive:withCompletionHandler:) method."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"userInfo: The ","type":"text"},{"code":"[AnyHashable : Any]","type":"codeVoice"},{"type":"text","text":" received within userNotificationCenter(_:didReceive:withCompletionHandler:) method."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"authenticationMethod: The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" is the authentication method that was used to authenticate the user"},{"text":" ","type":"text"},{"type":"text","text":"on the authenticating device, for example, fpt (fingerprint), face (facial recognition) etc."},{"type":"text","text":" "},{"type":"text","text":"Refer to the “amr” (Authentication Method Reference) values "},{"type":"reference","isActive":true,"identifier":"https:\/\/tools.ietf.org\/html\/rfc8176\/#section-2"}]}]}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"sections":[],"abstract":[{"type":"text","text":"Process remote notifcation action"}],"kind":"symbol","metadata":{"externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)processRemoteNotificationAction:authenticationMethod:forRemoteNotification:completionHandler:","role":"symbol","roleHeading":"Type Method","title":"processRemoteNotificationAction(_:authenticationMethod:forRemoteNotification:completionHandler:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"processRemoteNotificationAction"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"authenticationMethod"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forRemoteNotification"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"notificationObject"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationObject","text":"NotificationObject","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"PingOneSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"processRemoteNotificationAction:authenticationMethod:forRemoteNotification:completionHandler:","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/processRemoteNotificationAction(_:authenticationMethod:forRemoteNotification:completionHandler:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingone\/processremotenotificationaction(_:authenticationmethod:forremotenotification:completionhandler:)"]},{"paths":["\/documentation\/pingonesdk\/pingone\/processremotenotificationaction(_:authenticationmethod:forremotenotification:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"https://tools.ietf.org/html/rfc8176/#section-2":{"identifier":"https:\/\/tools.ietf.org\/html\/rfc8176\/#section-2","type":"link","title":"here","titleInlineContent":[{"text":"here","type":"text"}],"url":"https:\/\/tools.ietf.org\/html\/rfc8176\/#section-2"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"kind":"symbol","navigatorTitle":[{"text":"PingOne","kind":"identifier"}],"abstract":[],"url":"\/documentation\/pingonesdk\/pingone","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PingOne","kind":"identifier"}],"title":"PingOne"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/processRemoteNotificationAction(_:authenticationMethod:forRemoteNotification:completionHandler:)":{"kind":"symbol","abstract":[{"text":"Process remote notifcation action","type":"text"}],"navigatorTitle":[{"text":"processRemoteNotificationAction:authenticationMethod:forRemoteNotification:completionHandler:","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/processRemoteNotificationAction(_:authenticationMethod:forRemoteNotification:completionHandler:)","url":"\/documentation\/pingonesdk\/pingone\/processremotenotificationaction(_:authenticationmethod:forremotenotification:completionhandler:)","title":"processRemoteNotificationAction(_:authenticationMethod:forRemoteNotification:completionHandler:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"processRemoteNotificationAction"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationMethod"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"forRemoteNotification","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"notificationObject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationObject","text":"NotificationObject"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationObject"}],"kind":"symbol","abstract":[{"text":"A Notification Object represents an authentication request via remote notification. It can be approved or denied.","type":"text"}],"type":"topic","title":"NotificationObject","role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","navigatorTitle":[{"kind":"identifier","text":"NotificationObject"}],"url":"\/documentation\/pingonesdk\/notificationobject"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"url":"\/documentation\/pingonesdk","type":"topic","kind":"symbol","role":"collection","title":"PingOneSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"processRemoteNotificationAction:authenticationMethod:forRemoteNotification:completionHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"processRemoteNotificationAction:authenticationMethod:forRemoteNotification:completionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"processRemoteNotificationAction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"identifier"},{"text":" ","kind":"text"},{"text":"authenticationMethod:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"authenticationMethod"},{"text":" ","kind":"text"},{"text":"forRemoteNotification:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userInfo"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationObject","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","kind":"typeIdentifier","text":"NotificationObject"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","op":"replace","value":"PingOne"},{"value":[{"text":"PingOne","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments"},{"value":"processRemoteNotificationAction:authenticationMethod:forRemoteNotification:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1processRemoteNotificationAction(_:authenticationMethod:forRemoteNotification:completionHandler:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"processRemoteNotificationAction:authenticationMethod:forRemoteNotification:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1processRemoteNotificationAction(_:authenticationMethod:forRemoteNotification:completionHandler:)\/fragments"},{"op":"replace","value":"NotificationObject","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/fragments","value":[{"text":"NotificationObject","kind":"identifier"}],"op":"replace"}]}]}