{"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingone\/setdevicetoken(token:type:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pingone\/setdevicetoken(token:type:completionhandler:)"]}],"abstract":[{"type":"text","text":"Set device remote notification token"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDeviceToken","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"token"},{"text":" ","kind":"text"},{"text":"deviceToken","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"APNSDeviceTokenType","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType","kind":"typeIdentifier","preciseIdentifier":"s:10PingOneSDK0aB0C19APNSDeviceTokenTypeO"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"NSError in case of an error."}]}]},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Setting should be done within the "},{"type":"codeVoice","code":"application:didRegisterForRemoteNotificationsWithDeviceToken"},{"text":" method","type":"text"},{"type":"text","text":" "},{"type":"text","text":"in the appDelegate class."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"deviceToken: The ","type":"text"},{"type":"codeVoice","code":"Data"},{"text":" received within the ","type":"text"},{"code":"application:didRegisterForRemoteNotificationsWithDeviceToken","type":"codeVoice"},{"type":"text","text":" method."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"type: The "},{"code":"APNSDeviceTokenType","type":"codeVoice"},{"type":"text","text":" enum can be "},{"code":"production","type":"codeVoice"},{"type":"text","text":" or "},{"code":"sandbox","type":"codeVoice"},{"type":"text","text":" type."}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/setDeviceToken(token:type:completionHandler:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDeviceToken"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10PingOneSDK0aB0C19APNSDeviceTokenTypeO","text":"APNSDeviceTokenType"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"]?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Type Method","navigatorTitle":[{"text":"setDeviceTokenWithToken:type:completionHandler:","kind":"identifier"}],"role":"symbol","modules":[{"name":"PingOneSDK"}],"title":"setDeviceToken(token:type:completionHandler:)","symbolKind":"method","externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)setDeviceTokenWithToken:type:completionHandler:"},"sections":[],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/APNSDeviceTokenType":{"navigatorTitle":[{"text":"APNSDeviceTokenType","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"APNSDeviceTokenType","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Type that describes the APNS environment.","type":"text"}],"type":"topic","title":"PingOne.APNSDeviceTokenType"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/APNSDeviceTokenType":{"type":"topic","title":"APNSDeviceTokenType","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/APNSDeviceTokenType","url":"\/documentation\/pingonesdk\/apnsdevicetokentype","kind":"symbol","abstract":[{"type":"text","text":"Type that describes the APNS environment."},{"type":"text","text":" "},{"text":"It is possible to establish a connection between the PingOne server and one of the following Apple servers:","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Development ("},{"text":"sandbox","type":"text"},{"type":"text","text":") or "},{"text":"production","type":"text"},{"text":" server.","type":"text"}],"role":"symbol","fragments":[{"text":"APNSDeviceTokenType","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/setDeviceToken(token:type:completionHandler:)":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/setDeviceToken(token:type:completionHandler:)","url":"\/documentation\/pingonesdk\/pingone\/setdevicetoken(token:type:completionhandler:)","abstract":[{"text":"Set device remote notification token","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDeviceToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"APNSDeviceTokenType","kind":"typeIdentifier","preciseIdentifier":"s:10PingOneSDK0aB0C19APNSDeviceTokenTypeO"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"setDeviceToken(token:type:completionHandler:)","navigatorTitle":[{"text":"setDeviceTokenWithToken:type:completionHandler:","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PingOne","kind":"identifier"}],"navigatorTitle":[{"text":"PingOne","kind":"identifier"}],"abstract":[],"title":"PingOne","url":"\/documentation\/pingonesdk\/pingone"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setDeviceTokenWithToken:type:completionHandler:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setDeviceTokenWithToken:type:completionHandler:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setDeviceTokenWithToken:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deviceToken"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/APNSDeviceTokenType","preciseIdentifier":"c:@M@PingOneSDK@E@APNSDeviceTokenType","kind":"typeIdentifier","text":"APNSDeviceTokenType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<NSError *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1setDeviceToken(token:type:completionHandler:)\/title","op":"replace","value":"setDeviceTokenWithToken:type:completionHandler:"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1setDeviceToken(token:type:completionHandler:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setDeviceTokenWithToken:type:completionHandler:"}],"op":"replace"},{"value":"PingOne","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments","value":[{"text":"PingOne","kind":"identifier"}]}]}]}