{"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"please use setDeviceToken(deviceToken deviceToken: Data, type: APNSDeviceTokenType, completionHandler: @escaping (_ error: [NSError]?) -> Void) instead","type":"text"}]}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDeviceToken"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"deviceToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10PingOneSDK0aB0C19APNSDeviceTokenTypeO","text":"APNSDeviceTokenType","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"NSError in case of an error."}]}]},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Setting should be done within the ","type":"text"},{"type":"codeVoice","code":"application:didRegisterForRemoteNotificationsWithDeviceToken"},{"text":" method","type":"text"},{"text":" ","type":"text"},{"text":"in the appDelegate class.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"deviceToken: The ","type":"text"},{"code":"Data","type":"codeVoice"},{"type":"text","text":" received within the "},{"type":"codeVoice","code":"application:didRegisterForRemoteNotificationsWithDeviceToken"},{"type":"text","text":" method."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"type: The "},{"code":"APNSDeviceTokenType","type":"codeVoice"},{"text":" enum can be ","type":"text"},{"code":"production","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"sandbox"},{"type":"text","text":" type."}],"type":"paragraph"}]}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"PingOneSDK"}],"role":"symbol","title":"setDeviceToken(_:type:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setDeviceToken","kind":"identifier"},{"kind":"text","text":"("},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10PingOneSDK0aB0C19APNSDeviceTokenTypeO","text":"APNSDeviceTokenType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setDeviceToken:type:completionHandler:","kind":"identifier"}],"externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)setDeviceToken:type:completionHandler:","platforms":[]},"sections":[],"abstract":[{"text":"Set device remote notification token","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/setDeviceToken(_:type:completionHandler:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingone\/setdevicetoken(_:type:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pingone\/setdevicetoken(_:type:completionhandler:)"]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/setDeviceToken(_:type:completionHandler:)":{"title":"setDeviceToken(_:type:completionHandler:)","url":"\/documentation\/pingonesdk\/pingone\/setdevicetoken(_:type:completionhandler:)","navigatorTitle":[{"kind":"identifier","text":"setDeviceToken:type:completionHandler:"}],"deprecated":true,"abstract":[{"text":"Set device remote notification token","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/setDeviceToken(_:type:completionHandler:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDeviceToken"},{"kind":"text","text":"("},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10PingOneSDK0aB0C19APNSDeviceTokenTypeO","text":"APNSDeviceTokenType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PingOne","kind":"identifier"}],"navigatorTitle":[{"text":"PingOne","kind":"identifier"}],"abstract":[],"title":"PingOne","url":"\/documentation\/pingonesdk\/pingone"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/APNSDeviceTokenType":{"type":"topic","title":"APNSDeviceTokenType","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/APNSDeviceTokenType","url":"\/documentation\/pingonesdk\/apnsdevicetokentype","kind":"symbol","abstract":[{"type":"text","text":"Type that describes the APNS environment."},{"type":"text","text":" "},{"text":"It is possible to establish a connection between the PingOne server and one of the following Apple servers:","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Development ("},{"text":"sandbox","type":"text"},{"type":"text","text":") or "},{"text":"production","type":"text"},{"text":" server.","type":"text"}],"role":"symbol","fragments":[{"text":"APNSDeviceTokenType","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/APNSDeviceTokenType":{"navigatorTitle":[{"text":"APNSDeviceTokenType","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"APNSDeviceTokenType","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Type that describes the APNS environment.","type":"text"}],"type":"topic","title":"PingOne.APNSDeviceTokenType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"setDeviceToken:type:completionHandler:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setDeviceToken:type:completionHandler:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setDeviceToken:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deviceToken"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/APNSDeviceTokenType","kind":"typeIdentifier","text":"APNSDeviceTokenType","preciseIdentifier":"c:@M@PingOneSDK@E@APNSDeviceTokenType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1setDeviceToken(_:type:completionHandler:)\/title","value":"setDeviceToken:type:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1setDeviceToken(_:type:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setDeviceToken:type:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","value":"PingOne"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments","op":"replace","value":[{"kind":"identifier","text":"PingOne"}]}]}]}