{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"testRemoteNotification"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"region","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@E@PingOneRegion","text":"PingOneRegion","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"results","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","text":"NotificationTest"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest","kind":"typeIdentifier","text":"NotificationTest"},{"text":".","kind":"text"},{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum","kind":"typeIdentifier","text":"TestResult","preciseIdentifier":"s:10PingOneSDK16NotificationTestC0E6ResultO"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of "},{"type":"codeVoice","code":"NotificationTest"},{"text":" objects and ","type":"text"},{"code":"NSError","type":"codeVoice"},{"text":" in case of an error.","type":"text"}]}],"kind":"content"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/pingonesdk\/pingone\/testremotenotification(_:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pingone\/testremotenotification(_:completionhandler:)"]}],"abstract":[{"text":"Runs push notification tests","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/testRemoteNotification(_:completionHandler:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"testRemoteNotification","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@PingOneSDK@E@PingOneRegion","text":"PingOneRegion","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"results","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"NotificationTest","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"status","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest","text":"NotificationTest","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10PingOneSDK16NotificationTestC0E6ResultO","text":"TestResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"testRemoteNotification:completionHandler:"}],"modules":[{"name":"PingOneSDK"}],"symbolKind":"method","externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)testRemoteNotification:completionHandler:","role":"symbol","title":"testRemoteNotification(_:completionHandler:)"},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PingOne","kind":"identifier"}],"navigatorTitle":[{"text":"PingOne","kind":"identifier"}],"abstract":[],"title":"PingOne","url":"\/documentation\/pingonesdk\/pingone"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","title":"NotificationTest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NotificationTest","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"NotificationTest","kind":"identifier"}],"abstract":[{"type":"text","text":"Public class that contains data of notifications tests"}],"role":"symbol","type":"topic","url":"\/documentation\/pingonesdk\/notificationtest"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion","title":"PingOneRegion","url":"\/documentation\/pingonesdk\/pingoneregion","abstract":[{"type":"text","text":"Public enum that describes the regions available for PingOne SDK."}],"navigatorTitle":[{"kind":"identifier","text":"PingOneRegion"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PingOneRegion","kind":"identifier"}],"type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/testRemoteNotification(_:completionHandler:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/testRemoteNotification(_:completionHandler:)","title":"testRemoteNotification(_:completionHandler:)","url":"\/documentation\/pingonesdk\/pingone\/testremotenotification(_:completionhandler:)","abstract":[{"text":"Runs push notification tests","type":"text"}],"navigatorTitle":[{"text":"testRemoteNotification:completionHandler:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"testRemoteNotification","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PingOneRegion","preciseIdentifier":"c:@M@PingOneSDK@E@PingOneRegion","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"results"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest","kind":"typeIdentifier","text":"NotificationTest"},{"kind":"text","text":"]?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NotificationTest","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10PingOneSDK16NotificationTestC0E6ResultO","text":"TestResult","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/TestResult":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/TestResult","title":"TestResult","abstract":[{"type":"text","text":"Public enum that describes the notification test result."}],"url":"\/documentation\/pingonesdk\/testresult","fragments":[{"kind":"identifier","text":"TestResult"}],"type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/TestResult-swift.enum":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TestResult"}],"navigatorTitle":[{"kind":"identifier","text":"TestResult"}],"abstract":[{"type":"text","text":"Public enum that describes the notification test result."}],"title":"NotificationTest.TestResult","url":"\/documentation\/pingonesdk\/notificationtest\/testresult-swift.enum"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","value":"testRemoteNotification:completionHandler:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"testRemoteNotification:completionHandler:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"testRemoteNotification:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PingOneRegion","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@E@PingOneRegion","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"region"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"NSArray<NotificationTest *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"TestResult","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/TestResult","preciseIdentifier":"c:@M@PingOneSDK@E@TestResult"},{"kind":"text","text":" "},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PingOne","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title"},{"value":[{"kind":"identifier","text":"PingOne"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/title","op":"replace","value":"NotificationTest"},{"op":"replace","value":[{"kind":"identifier","text":"NotificationTest"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/fragments"},{"value":"PingOneRegion","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/fragments","op":"replace","value":[{"kind":"identifier","text":"PingOneRegion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1testRemoteNotification(_:completionHandler:)\/title","value":"testRemoteNotification:completionHandler:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"testRemoteNotification:completionHandler:"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1testRemoteNotification(_:completionHandler:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}