{"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"errorCode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"errorCode"}],"modules":[{"name":"PingOneSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"externalID":"c:@M@PingOneSDK@objc(cs)AuthenticatorModel(py)errorCode"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/errorCode"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel"]]},"abstract":[{"text":"Error message in case of authorization method failure","type":"text"}],"variants":[{"paths":["\/documentation\/pingonesdk\/authenticatormodel\/errorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/authenticatormodel\/errorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel","url":"\/documentation\/pingonesdk\/authenticatormodel","title":"AuthenticatorModel","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticatorModel","kind":"identifier"}],"navigatorTitle":[{"text":"AuthenticatorModel","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"AuthenticatorModel public class contains the acceptable authorization methods and its status"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel/errorCode":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorCode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/errorCode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"errorCode"}],"title":"errorCode","abstract":[{"type":"text","text":"Error message in case of authorization method failure"}],"type":"topic","url":"\/documentation\/pingonesdk\/authenticatormodel\/errorcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"errorCode"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"errorCode"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"errorCode"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"AuthenticatorModel","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/fragments","op":"replace","value":[{"text":"AuthenticatorModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel~1errorCode\/title","value":"errorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel~1errorCode\/fragments","value":[{"text":"errorCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}