{"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/notNeeded","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"notNeeded","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus"]]},"abstract":[{"type":"text","text":"There is no PingID data that has to be migrated."}],"sections":[],"metadata":{"navigatorTitle":[{"text":"MigrationStatusNotNeeded","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notNeeded"}],"title":"MigrationStatus.notNeeded","externalID":"c:@M@PingOneSDK@E@MigrationStatus@MigrationStatusNotNeeded","modules":[{"name":"PingOneSDK"}],"role":"symbol","roleHeading":"Case","symbolKind":"case"},"variants":[{"paths":["\/documentation\/pingonesdk\/migrationstatus\/notneeded"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/migrationstatus\/notneeded"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus":{"abstract":[{"text":"Enum that represents the migration status returned from the SDK","type":"text"}],"type":"topic","title":"MigrationStatus","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus","url":"\/documentation\/pingonesdk\/migrationstatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MigrationStatus"}],"kind":"symbol","navigatorTitle":[{"text":"MigrationStatus","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus/notNeeded":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notNeeded"}],"title":"MigrationStatus.notNeeded","url":"\/documentation\/pingonesdk\/migrationstatus\/notneeded","role":"symbol","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/notNeeded","abstract":[{"type":"text","text":"There is no PingID data that has to be migrated."}],"navigatorTitle":[{"text":"MigrationStatusNotNeeded","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MigrationStatusNotNeeded","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MigrationStatusNotNeeded","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MigrationStatusNotNeeded","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus\/title","value":"MigrationStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus\/fragments","value":[{"text":"MigrationStatus","kind":"identifier"}],"op":"replace"},{"value":"MigrationStatusNotNeeded","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1notNeeded\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1notNeeded\/fragments","value":[{"text":"MigrationStatusNotNeeded","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}