{"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/temporaryFailed","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MigrationStatusTemporaryFailed"}],"title":"MigrationStatus.temporaryFailed","role":"symbol","symbolKind":"case","modules":[{"name":"PingOneSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"temporaryFailed","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@PingOneSDK@E@MigrationStatus@MigrationStatusTemporaryFailed"},"abstract":[{"text":"Migration failed due to server error, client can try again.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/pingonesdk\/migrationstatus\/temporaryfailed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/migrationstatus\/temporaryfailed"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"temporaryFailed"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus/temporaryFailed":{"abstract":[{"text":"Migration failed due to server error, client can try again.","type":"text"}],"type":"topic","url":"\/documentation\/pingonesdk\/migrationstatus\/temporaryfailed","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/temporaryFailed","title":"MigrationStatus.temporaryFailed","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"temporaryFailed","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MigrationStatusTemporaryFailed","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus":{"abstract":[{"text":"Enum that represents the migration status returned from the SDK","type":"text"}],"type":"topic","title":"MigrationStatus","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus","url":"\/documentation\/pingonesdk\/migrationstatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MigrationStatus"}],"kind":"symbol","navigatorTitle":[{"text":"MigrationStatus","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MigrationStatusTemporaryFailed","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MigrationStatusTemporaryFailed"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MigrationStatusTemporaryFailed","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1temporaryFailed\/title","value":"MigrationStatusTemporaryFailed","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MigrationStatusTemporaryFailed"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1temporaryFailed\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus\/title","op":"replace","value":"MigrationStatus"},{"value":[{"text":"MigrationStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}