{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Australia"},"metadata":{"title":"PingOneRegion.Australia","navigatorTitle":[{"text":"PingOneRegionAustralia","kind":"identifier"}],"modules":[{"name":"PingOneSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Australia"}],"externalID":"c:@M@PingOneSDK@E@PingOneRegion@PingOneRegionAustralia","symbolKind":"case","roleHeading":"Case","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Australia"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Australia","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingoneregion\/australia"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pingoneregion\/australia"]}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion"]]},"sections":[],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion","title":"PingOneRegion","url":"\/documentation\/pingonesdk\/pingoneregion","abstract":[{"type":"text","text":"Public enum that describes the regions available for PingOne SDK."}],"navigatorTitle":[{"kind":"identifier","text":"PingOneRegion"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PingOneRegion","kind":"identifier"}],"type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion/Australia":{"navigatorTitle":[{"text":"PingOneRegionAustralia","kind":"identifier"}],"title":"PingOneRegion.Australia","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"Australia","kind":"identifier"}],"abstract":[{"text":"Australia","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Australia","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pingonesdk\/pingoneregion\/australia"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"PingOneRegionAustralia","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"PingOneRegionAustralia","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"PingOneRegionAustralia","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/title","value":"PingOneRegion"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/fragments","value":[{"kind":"identifier","text":"PingOneRegion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1Australia\/title","value":"PingOneRegionAustralia"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1Australia\/fragments","value":[{"kind":"identifier","text":"PingOneRegionAustralia"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}