{"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion"]]},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"AustraliaCom","kind":"identifier"}],"externalID":"c:@M@PingOneSDK@E@PingOneRegion@PingOneRegionAustraliaCom","modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"text":"PingOneRegionAustraliaCom","kind":"identifier"}],"role":"symbol","title":"PingOneRegion.AustraliaCom","symbolKind":"case","roleHeading":"Case"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/AustraliaCom"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AustraliaCom"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Australia Com","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingoneregion\/australiacom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pingoneregion\/australiacom"]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","url":"\/documentation\/pingonesdk","role":"collection","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion/AustraliaCom":{"navigatorTitle":[{"text":"PingOneRegionAustraliaCom","kind":"identifier"}],"kind":"symbol","title":"PingOneRegion.AustraliaCom","abstract":[{"text":"Australia Com","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/AustraliaCom","url":"\/documentation\/pingonesdk\/pingoneregion\/australiacom","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AustraliaCom"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneRegion"}],"title":"PingOneRegion","abstract":[{"text":"Public enum that describes the regions available for PingOne SDK.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"PingOneRegion","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion","url":"\/documentation\/pingonesdk\/pingoneregion","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PingOneRegionAustraliaCom"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PingOneRegionAustraliaCom"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"PingOneRegionAustraliaCom","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"PingOneRegionAustraliaCom","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1AustraliaCom\/title"},{"value":[{"kind":"identifier","text":"PingOneRegionAustraliaCom"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1AustraliaCom\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/title","op":"replace","value":"PingOneRegion"},{"value":[{"kind":"identifier","text":"PingOneRegion"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}