{"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion"]]},"metadata":{"title":"PingOneRegion.Canada","navigatorTitle":[{"kind":"identifier","text":"PingOneRegionCanada"}],"role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"Canada","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@PingOneSDK@E@PingOneRegion@PingOneRegionCanada","modules":[{"name":"PingOneSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingoneregion\/canada"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pingoneregion\/canada"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Canada","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"Canada","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Canada","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","url":"\/documentation\/pingonesdk","role":"collection","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion/Canada":{"title":"PingOneRegion.Canada","navigatorTitle":[{"text":"PingOneRegionCanada","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"Canada","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Canada","abstract":[{"text":"Canada","type":"text"}],"url":"\/documentation\/pingonesdk\/pingoneregion\/canada"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneRegion"}],"title":"PingOneRegion","abstract":[{"text":"Public enum that describes the regions available for PingOne SDK.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"PingOneRegion","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion","url":"\/documentation\/pingonesdk\/pingoneregion","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PingOneRegionCanada","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"PingOneRegionCanada"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PingOneRegionCanada"}]}],"kind":"declarations"},"op":"replace"},{"value":"PingOneRegionCanada","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1Canada\/title","op":"replace"},{"value":[{"text":"PingOneRegionCanada","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1Canada\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/title","value":"PingOneRegion"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/fragments","value":[{"text":"PingOneRegion","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}