{"abstract":[{"type":"text","text":"Europe"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion"]]},"sections":[],"metadata":{"title":"PingOneRegion.Europe","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"Europe","kind":"identifier"}],"modules":[{"name":"PingOneSDK"}],"symbolKind":"case","externalID":"c:@M@PingOneSDK@E@PingOneRegion@PingOneRegionEurope","role":"symbol","navigatorTitle":[{"text":"PingOneRegionEurope","kind":"identifier"}],"roleHeading":"Case"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Europe"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/pingonesdk\/pingoneregion\/europe"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pingoneregion\/europe"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Europe"},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion","title":"PingOneRegion","url":"\/documentation\/pingonesdk\/pingoneregion","abstract":[{"type":"text","text":"Public enum that describes the regions available for PingOne SDK."}],"navigatorTitle":[{"kind":"identifier","text":"PingOneRegion"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PingOneRegion","kind":"identifier"}],"type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion/Europe":{"navigatorTitle":[{"text":"PingOneRegionEurope","kind":"identifier"}],"title":"PingOneRegion.Europe","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Europe"}],"abstract":[{"text":"Europe","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/Europe","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pingonesdk\/pingoneregion\/europe"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PingOneRegionEurope","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PingOneRegionEurope"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PingOneRegionEurope"}],"languages":["occ"]}]}},{"value":"PingOneRegion","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/fragments","value":[{"text":"PingOneRegion","kind":"identifier"}]},{"value":"PingOneRegionEurope","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1Europe\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1Europe\/fragments","value":[{"text":"PingOneRegionEurope","kind":"identifier"}],"op":"replace"}]}]}