{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/NorthAmerica"},"variants":[{"paths":["\/documentation\/pingonesdk\/pingoneregion\/northamerica"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pingoneregion\/northamerica"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion"]]},"abstract":[{"text":"North America","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NorthAmerica","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Case","title":"PingOneRegion.NorthAmerica","externalID":"c:@M@PingOneSDK@E@PingOneRegion@PingOneRegionNorthAmerica","navigatorTitle":[{"text":"PingOneRegionNorthAmerica","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NorthAmerica"}],"modules":[{"name":"PingOneSDK"}],"symbolKind":"case","role":"symbol"},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion","title":"PingOneRegion","url":"\/documentation\/pingonesdk\/pingoneregion","abstract":[{"type":"text","text":"Public enum that describes the regions available for PingOne SDK."}],"navigatorTitle":[{"kind":"identifier","text":"PingOneRegion"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PingOneRegion","kind":"identifier"}],"type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion/NorthAmerica":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion\/NorthAmerica","type":"topic","kind":"symbol","abstract":[{"text":"North America","type":"text"}],"title":"PingOneRegion.NorthAmerica","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PingOneRegionNorthAmerica"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NorthAmerica","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/pingoneregion\/northamerica"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PingOneRegionNorthAmerica","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"PingOneRegionNorthAmerica"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PingOneRegionNorthAmerica"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/title","value":"PingOneRegion","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PingOneRegion"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/fragments"},{"value":"PingOneRegionNorthAmerica","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1NorthAmerica\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion~1NorthAmerica\/fragments","value":[{"text":"PingOneRegionNorthAmerica","kind":"identifier"}],"op":"replace"}]}]}