{"variants":[{"paths":["\/documentation\/pingonesdk"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk"]}],"hierarchy":{"paths":[[]]},"metadata":{"roleHeading":"Framework","title":"PingOneSDK","externalID":"PingOneSDK","symbolKind":"module","role":"collection","modules":[{"name":"PingOneSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK"},"topicSections":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"],"title":"Classes"},{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion"],"title":"Enumerations"}],"sections":[],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/APNSDeviceTokenType":{"type":"topic","title":"APNSDeviceTokenType","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/APNSDeviceTokenType","url":"\/documentation\/pingonesdk\/apnsdevicetokentype","kind":"symbol","abstract":[{"type":"text","text":"Type that describes the APNS environment."},{"type":"text","text":" "},{"text":"It is possible to establish a connection between the PingOne server and one of the following Apple servers:","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Development ("},{"text":"sandbox","type":"text"},{"type":"text","text":") or "},{"text":"production","type":"text"},{"text":" server.","type":"text"}],"role":"symbol","fragments":[{"text":"APNSDeviceTokenType","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationType":{"abstract":[{"type":"text","text":"Type that describes the purpose of the notification."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationType","url":"\/documentation\/pingonesdk\/notificationtype","role":"symbol","fragments":[{"kind":"identifier","text":"NotificationType"}],"title":"NotificationType"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneRegion":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion","title":"PingOneRegion","url":"\/documentation\/pingonesdk\/pingoneregion","abstract":[{"type":"text","text":"Public enum that describes the regions available for PingOne SDK."}],"navigatorTitle":[{"kind":"identifier","text":"PingOneRegion"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PingOneRegion","kind":"identifier"}],"type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"abstract":[{"text":"PingOne SDK error codes.","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/errorcode"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorStatus":{"url":"\/documentation\/pingonesdk\/authenticatorstatus","type":"topic","abstract":[],"role":"symbol","kind":"symbol","title":"AuthenticatorStatus","fragments":[{"text":"AuthenticatorStatus","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorStatus"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus":{"abstract":[{"text":"Enum that represents the migration status returned from the SDK","type":"text"}],"type":"topic","title":"MigrationStatus","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus","url":"\/documentation\/pingonesdk\/migrationstatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MigrationStatus"}],"kind":"symbol","navigatorTitle":[{"text":"MigrationStatus","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/TestType":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/TestType","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"TestType","kind":"identifier"}],"abstract":[{"text":"Public enum that describes the notification of all tests name, description, and resulstsInfo.","type":"text"}],"title":"TestType","url":"\/documentation\/pingonesdk\/testtype"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel","url":"\/documentation\/pingonesdk\/authenticatormodel","title":"AuthenticatorModel","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticatorModel","kind":"identifier"}],"navigatorTitle":[{"text":"AuthenticatorModel","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"AuthenticatorModel public class contains the acceptable authorization methods and its status"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject":{"title":"AuthenticationObject","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject","url":"\/documentation\/pingonesdk\/authenticationobject","navigatorTitle":[{"kind":"identifier","text":"AuthenticationObject"}],"abstract":[{"text":"Public class that contains data of authenticate with code response","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationObject"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorType":{"type":"topic","fragments":[{"kind":"identifier","text":"AuthenticatorType"}],"kind":"symbol","title":"AuthenticatorType","url":"\/documentation\/pingonesdk\/authenticatortype","abstract":[],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorType"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneVersionString":{"role":"symbol","url":"\/documentation\/pingonesdk\/pingoneversionstring","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneVersionString","title":"PingOneVersionString","abstract":[{"type":"text","text":"Project version string for PingOne."}],"type":"topic","fragments":[{"text":"PingOneVersionString","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneVersionNumber":{"fragments":[{"text":"PingOneVersionNumber","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneVersionNumber","type":"topic","kind":"symbol","role":"symbol","title":"PingOneVersionNumber","abstract":[{"text":"Project version number for PingOne.","type":"text"}],"url":"\/documentation\/pingonesdk\/pingoneversionnumber"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject":{"url":"\/documentation\/pingonesdk\/notificationobject","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationObject","kind":"identifier"}],"title":"NotificationObject","navigatorTitle":[{"kind":"identifier","text":"NotificationObject"}],"abstract":[{"type":"text","text":"A Notification Object represents an authentication request via remote notification. It can be approved or denied."}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PairingObject":{"url":"\/documentation\/pingonesdk\/pairingobject","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PairingObject"}],"navigatorTitle":[{"kind":"identifier","text":"PairingObject"}],"title":"PairingObject","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"PairingObject represents a pairing request that can be approved or ignored."}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PairingInfo":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo","navigatorTitle":[{"text":"PairingInfo","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/pairinginfo","role":"symbol","title":"PairingInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PairingInfo"}],"kind":"symbol","abstract":[{"type":"text","text":"Public PairingInfo class contains data about pairing resolution"}],"type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","title":"NotificationTest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NotificationTest","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"NotificationTest","kind":"identifier"}],"abstract":[{"type":"text","text":"Public class that contains data of notifications tests"}],"role":"symbol","type":"topic","url":"\/documentation\/pingonesdk\/notificationtest"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/OneTimePasscodeInfo":{"navigatorTitle":[{"kind":"identifier","text":"OneTimePasscodeInfo"}],"title":"OneTimePasscodeInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OneTimePasscodeInfo"}],"abstract":[{"type":"text","text":"Public class that contains data of the One Time Passcode"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/onetimepasscodeinfo"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/TestResult":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/TestResult","title":"TestResult","abstract":[{"type":"text","text":"Public enum that describes the notification test result."}],"url":"\/documentation\/pingonesdk\/testresult","fragments":[{"kind":"identifier","text":"TestResult"}],"type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PingOne","kind":"identifier"}],"navigatorTitle":[{"text":"PingOne","kind":"identifier"}],"abstract":[],"title":"PingOne","url":"\/documentation\/pingonesdk\/pingone"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"],"title":"Classes"},{"title":"Variables","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneVersionNumber","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneVersionString"]},{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/APNSDeviceTokenType","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorStatus","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorType","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationType","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneRegion","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/TestResult","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/TestType"],"title":"Enumerations"}],"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/title","op":"replace","value":"PingOneRegion"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneRegion\/fragments","op":"replace","value":[{"text":"PingOneRegion","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus\/title","value":"MigrationStatus"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"MigrationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/title","value":"AuthenticatorModel"},{"value":[{"kind":"identifier","text":"AuthenticatorModel"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/fragments"},{"value":"AuthenticationObject","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/title","op":"replace"},{"value":[{"text":"AuthenticationObject","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/fragments"},{"value":"NotificationObject","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/fragments","value":[{"text":"NotificationObject","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingObject\/title","value":"PairingObject"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingObject\/fragments","value":[{"kind":"identifier","text":"PairingObject"}],"op":"replace"},{"op":"replace","value":"PairingInfo","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingInfo\/fragments","value":[{"text":"PairingInfo","kind":"identifier"}]},{"value":"NotificationTest","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/title"},{"op":"replace","value":[{"text":"NotificationTest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo\/title","value":"OneTimePasscodeInfo","op":"replace"},{"value":[{"text":"OneTimePasscodeInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo\/fragments"},{"value":"PingOne","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title"},{"value":[{"kind":"identifier","text":"PingOne"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments"}]}]}