{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cantUpdateRegion"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"modules":[{"name":"PingOneSDK"}],"title":"ErrorCode.cantUpdateRegion","roleHeading":"Case","externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodeCantUpdateRegion","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cantUpdateRegion"}],"symbolKind":"case","navigatorTitle":[{"text":"ErrorCodeCantUpdateRegion","kind":"identifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/cantUpdateRegion","interfaceLanguage":"swift"},"abstract":[{"text":"The device is already trusted with a certain region and cannot set a new one using configure(PingOneRegion). If needed to change the region, the device should be reset by calling the removePingOneLocalData() method.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/errorcode\/cantupdateregion"]},{"paths":["\/documentation\/pingonesdk\/errorcode\/cantupdateregion"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/cantUpdateRegion":{"navigatorTitle":[{"text":"ErrorCodeCantUpdateRegion","kind":"identifier"}],"title":"ErrorCode.cantUpdateRegion","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cantUpdateRegion","kind":"identifier"}],"abstract":[{"type":"text","text":"The device is already trusted with a certain region and cannot set a new one using configure(PingOneRegion). If needed to change the region, the device should be reset by calling the removePingOneLocalData() method."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/cantUpdateRegion","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/errorcode\/cantupdateregion"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"abstract":[{"text":"PingOne SDK error codes.","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/errorcode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ErrorCodeCantUpdateRegion"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeCantUpdateRegion"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ErrorCodeCantUpdateRegion"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1cantUpdateRegion\/title","value":"ErrorCodeCantUpdateRegion"},{"value":[{"kind":"identifier","text":"ErrorCodeCantUpdateRegion"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1cantUpdateRegion\/fragments","op":"replace"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","op":"replace"}]}]}