{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceIsNotPaired","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/errorcode\/deviceisnotpaired"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/errorcode\/deviceisnotpaired"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"metadata":{"title":"ErrorCode.deviceIsNotPaired","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deviceIsNotPaired"}],"modules":[{"name":"PingOneSDK"}],"roleHeading":"Case","externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodeDeviceIsNotPaired","navigatorTitle":[{"text":"ErrorCodeDeviceIsNotPaired","kind":"identifier"}],"symbolKind":"case"},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/deviceIsNotPaired","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Device is not paired."}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","url":"\/documentation\/pingonesdk","role":"collection","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/deviceIsNotPaired":{"kind":"symbol","title":"ErrorCode.deviceIsNotPaired","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/deviceIsNotPaired","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deviceIsNotPaired"}],"type":"topic","navigatorTitle":[{"text":"ErrorCodeDeviceIsNotPaired","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/errorcode\/deviceisnotpaired","abstract":[{"text":"Device is not paired.","type":"text"}],"role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"title":"ErrorCode","abstract":[{"type":"text","text":"PingOne SDK error codes."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","role":"symbol","url":"\/documentation\/pingonesdk\/errorcode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ErrorCode"}],"navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ErrorCodeDeviceIsNotPaired"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ErrorCodeDeviceIsNotPaired","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ErrorCodeDeviceIsNotPaired"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1deviceIsNotPaired\/title","value":"ErrorCodeDeviceIsNotPaired"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1deviceIsNotPaired\/fragments","value":[{"text":"ErrorCodeDeviceIsNotPaired","kind":"identifier"}]},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]}]}]}