{"variants":[{"paths":["\/documentation\/pingonesdk\/errorcode\/failedpolicyrequirements"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/errorcode\/failedpolicyrequirements"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"ErrorCode.failedPolicyRequirements","navigatorTitle":[{"text":"ErrorCodeFailedPolicyRequirements","kind":"identifier"}],"modules":[{"name":"PingOneSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failedPolicyRequirements","kind":"identifier"}],"externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodeFailedPolicyRequirements","symbolKind":"case","roleHeading":"Case","role":"symbol"},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/failedPolicyRequirements","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Mobile device does not comply with policy requirements."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedPolicyRequirements"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/failedPolicyRequirements":{"title":"ErrorCode.failedPolicyRequirements","navigatorTitle":[{"text":"ErrorCodeFailedPolicyRequirements","kind":"identifier"}],"abstract":[{"type":"text","text":"Mobile device does not comply with policy requirements."}],"type":"topic","url":"\/documentation\/pingonesdk\/errorcode\/failedpolicyrequirements","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedPolicyRequirements"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/failedPolicyRequirements"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"abstract":[{"text":"PingOne SDK error codes.","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/errorcode"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ErrorCodeFailedPolicyRequirements"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ErrorCodeFailedPolicyRequirements"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"ErrorCodeFailedPolicyRequirements","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ErrorCodeFailedPolicyRequirements","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1failedPolicyRequirements\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1failedPolicyRequirements\/fragments","value":[{"text":"ErrorCodeFailedPolicyRequirements","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title","value":"ErrorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","value":[{"text":"ErrorCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}