{"sections":[],"abstract":[{"type":"text","text":"Migration is currently in progress - you cannot make another API call until it is completed."}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"migrationAlreadyRunning"}],"navigatorTitle":[{"text":"ErrorCodeMigrationAlreadyRunning","kind":"identifier"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodeMigrationAlreadyRunning","roleHeading":"Case","title":"ErrorCode.migrationAlreadyRunning","modules":[{"name":"PingOneSDK"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/errorcode\/migrationalreadyrunning"]},{"paths":["\/documentation\/pingonesdk\/errorcode\/migrationalreadyrunning"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/migrationAlreadyRunning","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"migrationAlreadyRunning","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/migrationAlreadyRunning":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeMigrationAlreadyRunning"}],"kind":"symbol","title":"ErrorCode.migrationAlreadyRunning","type":"topic","abstract":[{"type":"text","text":"Migration is currently in progress - you cannot make another API call until it is completed."}],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/migrationAlreadyRunning","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"migrationAlreadyRunning","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/errorcode\/migrationalreadyrunning"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"url":"\/documentation\/pingonesdk","type":"topic","kind":"symbol","role":"collection","title":"PingOneSDK"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"abstract":[],"title":"ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/pingonesdk\/errorcode","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ErrorCodeMigrationAlreadyRunning"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ErrorCodeMigrationAlreadyRunning","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ErrorCodeMigrationAlreadyRunning"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1migrationAlreadyRunning\/title","value":"ErrorCodeMigrationAlreadyRunning"},{"value":[{"text":"ErrorCodeMigrationAlreadyRunning","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1migrationAlreadyRunning\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title","value":"ErrorCode"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}]}]}]}