{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePairingAlreadyRunning"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","title":"ErrorCode.pairingAlreadyRunning","externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodePairingAlreadyRunning","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pairingAlreadyRunning","kind":"identifier"}],"modules":[{"name":"PingOneSDK"}]},"sections":[],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pairingAlreadyRunning","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"pairingAlreadyRunning","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pingonesdk\/errorcode\/pairingalreadyrunning"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/errorcode\/pairingalreadyrunning"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"abstract":[{"type":"text","text":"Pairing is currently in progress - you cannot make another API call until it is completed."}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/pairingAlreadyRunning":{"title":"ErrorCode.pairingAlreadyRunning","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pairingAlreadyRunning"}],"url":"\/documentation\/pingonesdk\/errorcode\/pairingalreadyrunning","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pairingAlreadyRunning","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"ErrorCodePairingAlreadyRunning","kind":"identifier"}],"abstract":[{"type":"text","text":"Pairing is currently in progress - you cannot make another API call until it is completed."}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"url":"\/documentation\/pingonesdk","type":"topic","kind":"symbol","role":"collection","title":"PingOneSDK"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"abstract":[],"title":"ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/pingonesdk\/errorcode","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ErrorCodePairingAlreadyRunning","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodePairingAlreadyRunning"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ErrorCodePairingAlreadyRunning","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1pairingAlreadyRunning\/title","value":"ErrorCodePairingAlreadyRunning"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1pairingAlreadyRunning\/fragments","value":[{"kind":"identifier","text":"ErrorCodePairingAlreadyRunning"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title","value":"ErrorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","value":[{"text":"ErrorCode","kind":"identifier"}]}]}]}