{"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"passcodeNotValid"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/errorcode\/passcodenotvalid"]},{"paths":["\/documentation\/pingonesdk\/errorcode\/passcodenotvalid"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Client failed to verify due to invalid one time passcode sent to the server."}],"sections":[],"metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodePasscodeNotValid","title":"ErrorCode.passcodeNotValid","navigatorTitle":[{"text":"ErrorCodePasscodeNotValid","kind":"identifier"}],"modules":[{"name":"PingOneSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passcodeNotValid","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/passcodeNotValid"},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/passcodeNotValid":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/passcodeNotValid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"passcodeNotValid","kind":"identifier"}],"kind":"symbol","title":"ErrorCode.passcodeNotValid","type":"topic","navigatorTitle":[{"text":"ErrorCodePasscodeNotValid","kind":"identifier"}],"abstract":[{"type":"text","text":"Client failed to verify due to invalid one time passcode sent to the server."}],"role":"symbol","url":"\/documentation\/pingonesdk\/errorcode\/passcodenotvalid"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"abstract":[],"title":"ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/pingonesdk\/errorcode","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"url":"\/documentation\/pingonesdk","type":"topic","kind":"symbol","role":"collection","title":"PingOneSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ErrorCodePasscodeNotValid"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ErrorCodePasscodeNotValid"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ErrorCodePasscodeNotValid"}]}],"kind":"declarations"}},{"value":"ErrorCodePasscodeNotValid","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1passcodeNotValid\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1passcodeNotValid\/fragments","value":[{"text":"ErrorCodePasscodeNotValid","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title","value":"ErrorCode"},{"value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}