{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"metadata":{"modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePushConfirmationTimeout"}],"title":"ErrorCode.pushConfirmationTimeout","role":"symbol","externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodePushConfirmationTimeout","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushConfirmationTimeout"}],"roleHeading":"Case","symbolKind":"case"},"abstract":[{"type":"text","text":"Client confirmation delay responding to push notification, resulted in timeout."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/errorcode\/pushconfirmationtimeout"]},{"paths":["\/documentation\/pingonesdk\/errorcode\/pushconfirmationtimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pushConfirmationTimeout","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushConfirmationTimeout"}]}],"kind":"declarations"}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"abstract":[{"text":"PingOne SDK error codes.","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/errorcode"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/pushConfirmationTimeout":{"abstract":[{"text":"Client confirmation delay responding to push notification, resulted in timeout.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ErrorCodePushConfirmationTimeout","kind":"identifier"}],"title":"ErrorCode.pushConfirmationTimeout","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushConfirmationTimeout"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pushConfirmationTimeout","url":"\/documentation\/pingonesdk\/errorcode\/pushconfirmationtimeout","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ErrorCodePushConfirmationTimeout"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"ErrorCodePushConfirmationTimeout","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ErrorCodePushConfirmationTimeout"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1pushConfirmationTimeout\/title","value":"ErrorCodePushConfirmationTimeout"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1pushConfirmationTimeout\/fragments","value":[{"kind":"identifier","text":"ErrorCodePushConfirmationTimeout"}],"op":"replace"}]}]}