{"metadata":{"title":"ErrorCode.testPushAlreadyRunning","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeTestPushAlreadyRunning"}],"modules":[{"name":"PingOneSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"testPushAlreadyRunning","kind":"identifier"}],"externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodeTestPushAlreadyRunning","symbolKind":"case","roleHeading":"Case","role":"symbol"},"variants":[{"paths":["\/documentation\/pingonesdk\/errorcode\/testpushalreadyrunning"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/errorcode\/testpushalreadyrunning"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"testPushAlreadyRunning"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/testPushAlreadyRunning"},"sections":[],"kind":"symbol","abstract":[{"text":"Test remote notification is currently in progress - you cannot make another API call until it is completed.","type":"text"}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/testPushAlreadyRunning":{"title":"ErrorCode.testPushAlreadyRunning","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeTestPushAlreadyRunning"}],"abstract":[{"text":"Test remote notification is currently in progress - you cannot make another API call until it is completed.","type":"text"}],"type":"topic","url":"\/documentation\/pingonesdk\/errorcode\/testpushalreadyrunning","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"testPushAlreadyRunning"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/testPushAlreadyRunning"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"abstract":[{"text":"PingOne SDK error codes.","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/errorcode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"ErrorCodeTestPushAlreadyRunning","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"ErrorCodeTestPushAlreadyRunning","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ErrorCodeTestPushAlreadyRunning","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1testPushAlreadyRunning\/title","value":"ErrorCodeTestPushAlreadyRunning","op":"replace"},{"value":[{"text":"ErrorCodeTestPushAlreadyRunning","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1testPushAlreadyRunning\/fragments"},{"op":"replace","value":"ErrorCode","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace"}]}]}