{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unrecognizedRemoteNotification"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/unrecognizedRemoteNotification","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/pingonesdk\/errorcode\/unrecognizedremotenotification"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/errorcode\/unrecognizedremotenotification"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"abstract":[{"text":"Remote notification isn’t from PingOne.","type":"text"}],"metadata":{"externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodeUnrecognizedRemoteNotification","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unrecognizedRemoteNotification","kind":"identifier"}],"modules":[{"name":"PingOneSDK"}],"symbolKind":"case","title":"ErrorCode.unrecognizedRemoteNotification","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeUnrecognizedRemoteNotification"}],"role":"symbol"},"sections":[],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"title":"ErrorCode","abstract":[{"type":"text","text":"PingOne SDK error codes."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","role":"symbol","url":"\/documentation\/pingonesdk\/errorcode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ErrorCode"}],"navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","url":"\/documentation\/pingonesdk","role":"collection","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/unrecognizedRemoteNotification":{"navigatorTitle":[{"text":"ErrorCodeUnrecognizedRemoteNotification","kind":"identifier"}],"kind":"symbol","title":"ErrorCode.unrecognizedRemoteNotification","abstract":[{"text":"Remote notification isn’t from PingOne.","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/unrecognizedRemoteNotification","url":"\/documentation\/pingonesdk\/errorcode\/unrecognizedremotenotification","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unrecognizedRemoteNotification"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ErrorCodeUnrecognizedRemoteNotification"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"ErrorCodeUnrecognizedRemoteNotification","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ErrorCodeUnrecognizedRemoteNotification","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"ErrorCode","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments"},{"value":"ErrorCodeUnrecognizedRemoteNotification","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1unrecognizedRemoteNotification\/title"},{"value":[{"text":"ErrorCodeUnrecognizedRemoteNotification","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1unrecognizedRemoteNotification\/fragments"}]}]}