{"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/pingonesdk\/pairinginfo\/authenticatorsarray"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pairinginfo\/authenticatorsarray"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"authenticatorsArray","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)AuthenticatorModel","text":"AuthenticatorModel"},{"text":"]","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo\/authenticatorsArray","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"List of authentication methods and their statuses","type":"text"}],"metadata":{"externalID":"c:@M@PingOneSDK@objc(cs)PairingInfo(py)authenticatorsArray","title":"authenticatorsArray","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"authenticatorsArray","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@PingOneSDK@objc(cs)AuthenticatorModel","kind":"typeIdentifier","text":"AuthenticatorModel"},{"text":"]","kind":"text"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"authenticatorsArray"}],"modules":[{"name":"PingOneSDK"}]},"sections":[],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PairingInfo/authenticatorsArray":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo\/authenticatorsArray","abstract":[{"type":"text","text":"List of authentication methods and their statuses"}],"kind":"symbol","title":"authenticatorsArray","url":"\/documentation\/pingonesdk\/pairinginfo\/authenticatorsarray","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticatorsArray"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@PingOneSDK@objc(cs)AuthenticatorModel","kind":"typeIdentifier","text":"AuthenticatorModel"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"authenticatorsArray","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel","url":"\/documentation\/pingonesdk\/authenticatormodel","title":"AuthenticatorModel","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticatorModel","kind":"identifier"}],"navigatorTitle":[{"text":"AuthenticatorModel","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"AuthenticatorModel public class contains the acceptable authorization methods and its status"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PairingInfo":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingInfo","navigatorTitle":[{"text":"PairingInfo","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/pairinginfo","role":"symbol","title":"PairingInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PairingInfo"}],"kind":"symbol","abstract":[{"type":"text","text":"Public PairingInfo class contains data about pairing resolution"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"authenticatorsArray","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"authenticatorsArray"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<AuthenticatorModel *>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"authenticatorsArray"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingInfo~1authenticatorsArray\/title","value":"authenticatorsArray","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingInfo~1authenticatorsArray\/fragments","value":[{"text":"authenticatorsArray","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/title","value":"AuthenticatorModel"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/fragments","value":[{"text":"AuthenticatorModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingInfo\/title","value":"PairingInfo","op":"replace"},{"value":[{"kind":"identifier","text":"PairingInfo"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingInfo\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}