{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validFrom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/validFrom","interfaceLanguage":"swift"},"metadata":{"title":"validFrom","role":"symbol","externalID":"c:@M@PingOneSDK@objc(cs)OneTimePasscodeInfo(py)validFrom","navigatorTitle":[{"kind":"identifier","text":"validFrom"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"PingOneSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validFrom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"The time of creation of the passcode.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/onetimepasscodeinfo\/validfrom"]},{"paths":["\/documentation\/pingonesdk\/onetimepasscodeinfo\/validfrom"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"url":"\/documentation\/pingonesdk","role":"collection","title":"PingOneSDK","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/OneTimePasscodeInfo/validFrom":{"navigatorTitle":[{"kind":"identifier","text":"validFrom"}],"title":"validFrom","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validFrom"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The time of creation of the passcode."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/validFrom","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/onetimepasscodeinfo\/validfrom"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/OneTimePasscodeInfo":{"navigatorTitle":[{"kind":"identifier","text":"OneTimePasscodeInfo"}],"title":"OneTimePasscodeInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OneTimePasscodeInfo"}],"abstract":[{"type":"text","text":"Public class that contains data of the One Time Passcode"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/onetimepasscodeinfo"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"validFrom"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"validFrom"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validFrom"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"validFrom","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo~1validFrom\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo~1validFrom\/fragments","op":"replace","value":[{"text":"validFrom","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo\/title","value":"OneTimePasscodeInfo"},{"value":[{"kind":"identifier","text":"OneTimePasscodeInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}